### ISSUE TITLE
Support citext postgres type

### ISSUE THREAD

**Issue by lancecarlson** [diesel-rs/diesel#1000]
Likely this should be fine:

```
type Citext = Text
```

Also need to check if the right coersions exist and that codegen will place nice with citext[]

Notes from gitter^ :)

**Comment by killercup** [comment]
> The citext module provides a case-insensitive character string type, citext. Essentially, it internally calls lower when comparing values. Otherwise, it behaves almost exactly like text.
> 
> https://www.postgresql.org/docs/9.6/static/citext.html

**Comment by sgrif** [comment]
This will have the same caveats as varchar when it comes to arrays.

<img width="1285" alt="screen shot 2017-07-12 at 1 46 01 pm" src="https://user-images.githubusercontent.com/1529387/28136994-d8715f08-6708-11e7-8b18-3a67da37017e.png">
<img width="756" alt="screen shot 2017-07-12 at 1 49 00 pm" src="https://user-images.githubusercontent.com/1529387/28137005-e425bb1e-6708-11e7-97fe-a2d2239e9e73.png">

Other than that this should be fine. The binary representation is identical to text.

**Comment by Lukazoid** [comment]
Should this not be reopened now support for citext has been removed?

**Comment by sgrif** [comment]
No, this isn't something anybody on the team is actively working on -- We'll be publishing a new policy soon about what we're doing with the issue tracker, but we're moving towards issues open here either being on the team's roadmap or things that are good for new contributors. If you'd like to discuss implementing this feature, you can start a thread at discourse.diesel.rs

**Comment by Boscop** [comment]
Does this mean that citext is not supported anymore? Why? 
I really want to use citext for e.g. username and email address columns.

**Comment by sgrif** [comment]
@Boscop Because the support we had was broken, and requires a more complete solution. We only accepted it in the first place because it was initially thought that a type alias would be sufficient. In general we don't support extensions in Diesel proper, since they can easily live in third party crates. Supporting this type is no different than supporting any other custom type as I've mentioned in https://github.com/diesel-rs/diesel/issues/1624#issuecomment-379541186. If you're interested in supporting a crate for this and have questions after taking a swing at it feel free to ask in Gitter

**Comment by vidhanio** [comment]
`citext` support has been added to diesel as of the merging of #4021 and the release of diesel 2.2. :)
