### ISSUE TITLE
Set up Travis to test against specific minimum Rust version

### ISSUE THREAD

**Issue by hobofan** [diesel-rs/diesel#1100]
I just noticed that Diesel requires Rust 1.18, not 1.17 as claimed on the website. In order to make sure accidental bumping of minimum Rust versions doesn't happen in the future Travis can be set up to test a specific version of Rust besides the three main release channels.

**Comment by killercup** [comment]
Oh, good catch! Maybe we can set up another travis matrix entry to just build the examples—this way we ensure that the diesel crates can be build (as dependencies) but can use newer features in the test code. (I'm specifically thinking about some pending changes to how `include!` works doc tests.)

**Comment by sgrif** [comment]
@diesel-rs/core We need to make a decision on our policy for Rust versions. [RFC #1105](https://github.com/nox/rust-rfcs/blob/master/text/1105-api-evolution.md) does not explicitly state whether increasing the minimum required Rust version is considered a major breaking change or not. I think we need to explicitly decide whether we are allowed to increase our minimum required Rust version or not without a major version bump.

My vote is that yes, we should be allowed to increase our minimum supported Rust version in minor versions (but not patch versions). Updating to a new stable version should never be difficult. Future enhancements like specialization, overlapping marker traits, and generic associated types will make new features in Diesel possible, and we should be able to take advantage of that.

**Comment by killercup** [comment]
I've been thinking about this for a bit (basically since seeing [your tweet](https://twitter.com/sgrif/status/942150962512195584)), but don't have a definitive answer. Here are some arguments that come to mind:

- Applications written in Jan 2018 that have `diesel = "1"` in them will break if we release 1.1 that uses features added in Rust 1.25 unless the user also happens to update their compiler. So it is a breaking change.
- Important crates like regex treat requiring a new compiler version as breaking change (cf. <https://github.com/rust-lang/regex/pull/209>)
- Other important crates, like futures, bump the min rust version in a minor (here 0.1.x) version (cf. [0.1.15](https://github.com/alexcrichton/futures-rs/blob/a16b5ab62068b55f73a8ff4353c7961c2de422bc/CHANGELOG.md#0115---2017-08-24))
- Rust Epochs will happen, maybe even LTS releases.
- The unwillingness to release Diesel 2.0 in half a year is most likely only a psychological barrier

A pragmatic solution would be to trail a few month behind the latest compiler version. This probably won't help all the people who are using a Linux distro's Rust compiler version, but might cover a signification enough number cases.

**Comment by sgrif** [comment]
Fixed by #1714
