### ISSUE TITLE
Allow exluding tables from infer_schema!() macro

### ISSUE THREAD

**Issue by Boscop** [diesel-rs/diesel#1115]
Useful for [virtual FTS tables](https://github.com/diesel-rs/diesel/issues/1112) which don't have a primary key.
The only way is to manually write the schema for all other tables, which shouldn't be necessary.

Btw, excluding it in the cli doesn't work:
```
>diesel print-schema -b foo
thread 'main' panicked at 'Could not load table `foo`: StringError("Diesel only
supports tables with primary keys. Table foo has no primary key")', src\libcore\
result.rs:860:4
```

Btw, my diesel cli version is diesel 0.15.0.

**Comment by sgrif** [comment]
If nothing else, we should fix the behavior in `diesel print-schema`

**Comment by Eijebong** [comment]
I can't reproduce the `print-schema` bug :/

@Boscop What OS are you running ?

**Comment by Boscop** [comment]
Win 8.1

**Comment by pocket7878** [comment]
Any updates on this? Currently I'm trying to rewrite my API server from Rails to Rust.
But I can't use `infer_schema!` since rails using `schema_migrations` table to hold migration history, and it has no primary key.

**Comment by sgrif** [comment]
I haven't been able to reproduce the issue. Since `diesel print-schema` is the recommended usage, which does support blacklisting, I don't think there's a major need to add it to `infer_schema!` which is mainly intended for use while prototyping. If someone can provide steps to reproduce a bug in the blacklisting behavior of `diesel print-schema`, please open a new issue with full steps to reproduce, including a migration file to set up the schema in question.
