### ISSUE TITLE
`table!` fails when column name is named `bool`

### ISSUE THREAD

**Issue by Emilgardis** [diesel-rs/diesel#1204]
related #1110 

https://gitter.im/diesel-rs/diesel?at=59ca4bbbf7299e8f5373ae61

**Comment by sgrif** [comment]
Just to make sure this has up to date context:

The issue is limited only to columns called `bool`. The problem is in the code generated by `#[derive(QueryId)]`, where there is an associated const with the type `bool`. The solution to this is to have a type alias somewhere known (it actually doesn't even have to be in Diesel, we can just put it in the generated code), and reference that instead of `bool` directly. Eventually the language will provide `std::primitives::bool`, and we can change to referencing that when it lands in stable.

**Comment by sgrif** [comment]
This is a low priority bug, so I'm leaving it off the milestone. Happy to help a new contributor work on a patch though

**Comment by stevepentland** [comment]
In an effort to learn more about diesel, I'd like to take this one on @sgrif. I'm just looking through what I believe is the code you referenced in your previous comment.

**Comment by sgrif** [comment]
:+1: Feel free to ask in Gitter if you have questions.

**Comment by YetAnotherMinion** [comment]
Related, the column name `nodes` also causes the table macro to fail. One of diesel's internal modules is named `nodes` and that causes an ambiguous import when the table macro is expanded.

**Comment by jhpratt** [comment]
@sgrif I presume this would be related to the bug I'm running into with a column named `columns`?

**Comment by fmartini** [comment]
All public modules declared in the `query_builder` module clash with column names in the table macro, e.g. `functions`.
