### ISSUE TITLE
embedded_migrations::revert missing

### ISSUE THREAD

**Issue by agentsim** [diesel-rs/diesel#1366]
After generating migrations with `embed_migrations!`, the resulting module does not include the `revert` method.

I would like to `revert` and then `run` migrations before each unit test, guaranteeing a clean database before each test invocation.

**Comment by sgrif** [comment]
We've purposely excluded the `revert` method, because what it does is dependent on which migrations have or haven't been run, and we don't expose that information.

Dropping and recreating your database is not recommended for tests. Instead, you should run your tests in a transaction. We provide [`begin_test_transaction`] and [`test_transaction`] for this purpose.

[`begin_test_transaction`]: http://docs.diesel.rs/diesel/connection/trait.Connection.html#method.begin_test_transaction
[`test_transaction`]: http://docs.diesel.rs/diesel/connection/trait.Connection.html#method.test_transaction
