### ISSUE TITLE
"cargo install diesel_cli" fails with a generic overflow on latest nightly

### ISSUE THREAD

**Issue by blm768** [diesel-rs/diesel#1450]
I'm running `cargo install diesel_cli` on a fairly fresh installation of Arch Linux, and `cargo` is spitting out an error message partway through the process:
```
$ cargo install diesel_cli
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing diesel_cli v1.0.0
   Compiling [[a bunch of dependency crates]]
   Compiling diesel v1.0.0
error[E0275]: overflow evaluating the requirement `<&_ as insertable::Insertable<_>>::Values`
  |
  = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `std::option::Option<&_>`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&std::option::Option<_>`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `std::option::Option<&std::option::Option<_>>`
  = note: required because of the requirements on the impl of `insertable::Insertable<_>` for `&std::option::Option<std::option::Option<_>>`
[[more lines of increasingly deeply nested Options]]
```
It seems to compile and install fine on stable, though, so it shouldn't be a significant issue unless it's also affecting other users.

What makes this particularly odd is that compiling Diesel as a project dependency works just fine for me on nightly; it's only `cargo install diesel_cli` that chokes on the `diesel` crate. Is anyone else seeing this behavior?

### Versions

- **Rust:** 1.24.0-nightly
- **Diesel:** 1.0.0
- **Operating System**: Linux (Arch)

**Comment by virome** [comment]
This seems to be a known regression in nightly rust, I believe this is the same issue that was encountered on Diesel's nightly ci builds

https://github.com/rust-lang/rust/issues/47139

**Comment by sgrif** [comment]
Yes, this is an issue in Rust not Diesel.

**Comment by AyushyaChitransh** [comment]
It would be very useful to mention here which version of rust solves the issue.

From the link to comments, it seems that the problem was solved by this [commit](https://github.com/rust-lang/rust/commit/56733bc9f8302409a2b6110f422512923c878154), but am unable to install diesel_cli using following versions:

 - nightly-x86_64-apple-darwin unchanged - rustc 1.26.0-nightly (80785a547 2018-03-30)
 - stable-x86_64-apple-darwin unchanged - rustc 1.25.0 (84203cac6 2018-03-25)

**Comment by AyushyaChitransh** [comment]
My build was failing but not due to the reasons mentioned in this issue. I was getting following error:

```
error: linking with `cc` failed: exit code: 1
 |
  = note: "cc" "-m64" "-L" ...
  ...
  = note: ld: library not found for -lmysqlclient
```

And I was able to resolve it by using:

`cargo install diesel_cli --no-default-features --features postgres`

Thanks to the [comment](https://github.com/diesel-rs/diesel/issues/321#issuecomment-218052134)
