### ISSUE TITLE
Support database views in diesel print-schema

### ISSUE THREAD

**Issue by lukesutton** [diesel-rs/diesel#1482]
## Problem Description

The `diesel print-schema` command doesn't output definitions for database views in Postgresql.

### What are you trying to accomplish?

For more complex queries I would like to be able to create a view in the database and associate it with a `Queryable` struct. This would be especially useful, since Postgresql now has support for materialized views.

### What is the expected output?

I would expect the diesel cli to output macro calls for views. If not by default then as an option.

### What is the actual output?

All tables, but no views.

**Comment by sgrif** [comment]
Unfortunately, we can't really do this until we more generally separate "data sources" from "tables". The problem is that all tables in Diesel must have a primary key, and there's no way that we could infer that. Humans can just pick a random arbitrary column and call that the primary key (and many views actually do logically have one), but I don't want to do that in Diesel CLI

**Comment by lukesutton** [comment]
Totally fair! I imagined there was some constraint there. My approach at this point has been to synthesize a primary key for rows in views and manually add `table!` declarations for them, which is working pretty well.

**Comment by sgrif** [comment]
Yup, that's the work around. For the record, I closed *this* issue, because that specific feature is not something we can support. That said, I *do* want to support views in general, as a separate concept from `table!`/`Table` (basically just not having a primary key), and when we do that they will absolutely be inferred by `diesel print-schema` and `infer_schema!`

**Comment by gojesandeep** [comment]
Is there any progress on support for views. I am looking to get something like http://postgrest.org/ done in rust and Diesel.

**Comment by weiznich** [comment]
@gojesandeep Nothing new here. 
For something like postgrest you may want to look at [wundergraph](https://github.com/weiznich/wundergraph), though that provides a graphql api instead of an rest api.

**Comment by martinellison** [comment]
I am currently trying the following steps (my view is `item_by_level`).

- need to do the following in sqlite3
- CREATE TABLE item_by_level_copy AS SELECT * FROM item_by_level;
- SELECT sql FROM sqlite_master WHERE name = "item_by_level_copy";
- edit the SQL to make ident the primary key and change the table name
- then run the SQL to create the new table
- then drop item_by_level_copy
- then run `diesel print-schema`
- then rename the new table back to item_by_level in the diesel schema

This gives me a schema, though all the columns are nullable.
