### ISSUE TITLE
Feature request: Table migration based on structs

### ISSUE THREAD

**Issue by flip111** [diesel-rs/diesel#1590]
I searched to see if this was requested before, it seems a bit similar to https://github.com/diesel-rs/diesel/issues/1086 but this issue is only about structural migration (DDL - data definitional language, subset of SQL).

Could diesel detect changes in Queryable and Insertable structs and write migration code to `up.sql` and `down.sql`?

This is very common in many orm's and frameworks. I personally know this functionality from Doctrine (PHP) and Django (Python) i suspect Rails (Ruby) has it too.

On a side note: this is kind of the reverse of https://github.com/diesel-rs/diesel/issues/1589

**Comment by sgrif** [comment]
https://github.com/diesel-rs/diesel/issues/1583#issuecomment-370186178

**Comment by flip111** [comment]
Hi, thanks for your response. With the discussion about `down` migrations and DSL's does your comment also apply to `up`  migrations based on generating SQL from queryable/insertable structs? I might be missing some background information, i couldn't tell.

**Comment by sgrif** [comment]
Sorry, I left out some context from previous discussions about this.

I don't think there's enough value in a rust-based migration DSL to justify the cost of maintenance. The only argument I've heard in favor of them (other than "I just don't want to write SQL migrations", which I don't find compelling) is that you're able to get down for free. I don't think that use case is compelling enough for such a feature to live within Diesel itself. I'm happy to help others implement it as a third party plugin.

Systems like Django ORM in Python or Data Mapper in Ruby where the migrations are generated from a model don't make much sense for Diesel, since structs which implement `Queryable` are not assumed to be one-to-one with a database table.

**Comment by flip111** [comment]
What if you take the fields of all structs that related to a single table. Put them in a (single) unique list. Compare that with the database columns. When the database has an extra column or is missing a column write out the SQL migration for it?

Are the facilities there to inspect the mapping (structs - tables)? Or would one have to write their own macros for it?

**Comment by sgrif** [comment]
Diesel doesn't assume or enforce that your structs are in anyway tied to table schema. If you wanted to write a library built around that for use with Diesel, I'd be happy to help with implementation questions.

**Comment by flip111** [comment]
> Diesel doesn't assume or enforce that your structs are in anyway tied to table schema.

As far as i know that is the definition of Object-Relational Mapping to do just that. Now i'm utterly confused.

**Comment by sgrif** [comment]
`Queryable` represents the result of a SQL query, which may or may not represent the entirety of a single database table. Often they represent only a few columns of a table, values from multiple tables, or values which aren't representative of a single database column at all

**Comment by sgrif** [comment]
Or to put it another way, `table!` declarations are what *is* one-to-one with your database schema in Diesel. We choose to generate those from your database schema, rather than generating your database schema from Rust declarations. You have to write one of those two, we chose the one which more precisely represents what you actually mean

**Comment by flip111** [comment]
I understood the Queryable/Insertable structs to be the value containing "objects" (the O in ORM). Can `table!` hold values? I mean the values that go into and come from the database.

In the docs i see `#[table_name = "posts"]` i think this annotation does tie the struct below it to the `posts` table. Or is nothing assumed/enforced here? No check with the schema (`table!`)? If not, what is the `posts` string used for?

I'm just trying to understand this by the background of another (non-rust) ORM i used to work with ...

**Comment by sgrif** [comment]
#[table_name] is used by other traits, but not by `Queryable`

**Comment by flip111** [comment]
The library looks well made, thanks for writing it. However i must conclude this is not an ORM. As far as i understood the insertable are based on the names of fields and the queryable on the order of fields. This does not give the user the freedom to create a mapping.

For relations i read in https://docs.diesel.rs/diesel/associations/index.html

> Associated data is typically loaded in multiple queries (one query per table). This is usually more efficient than using a join, especially if 3 or more tables are involved. For most datasets, using a join to load in a single query transmits so much duplicate data that it costs more time than the extra round trip would have.

I like to see some numbers with the claim of efficient. Traditional database wisdom says to use joins for maximum query performance and a single roundtrip. It is expensive to deduplicate the data for sure. But it also gives you the possibility to construct an [object graph](http://www.elegantcoding.com/2011/08/object-graph.html) and manage relations.

From that point many ORM's introduce the concept of Unit of Work where changes are made to the objects and then once committed update the database in the least amount of changes. This isn't necessary though but it gives you the opportunity to decouple your data changes with your database inserts.

ORM's have their own problems though, so this query-first approach is excellent in many cases. Again  diesel looks like a very good library ... i just went in with the wrong expectations i think after seeing "ORM".

**Comment by sgrif** [comment]
I'm not interested in debating the meaning of the term ORM. Thanks for bringing up your concerns. :)

**Comment by xdevs23** [comment]
I apologize for my difficulty understanding this, but I can't seem to derive the conclusion on this discussion. Does this mean that we can't generate a schema or a diff based on a rust struct?
Does this mean that I have to write the migration myself first, then run the migration, then let diesel generate the model and schema for it?
Is there a way around this? I would love to just write the struct and let diesel generate the schema and the migrations for me. 

This would conflict with that I've read, though.

The documentation states:

> Typically the schema module isn’t created by hand, it gets generated by diesel CLI. When we ran diesel setup, a file called [diesel.toml](https://github.com/diesel-rs/diesel/blob/2.2.x/examples/postgres/getting_started_step_1/diesel.toml) was created which tells Diesel to maintain a file at src/schema.rs for us. The file should look like this:

and

> If you prefer to generate your migrations based on Rust code instead, the diesel CLI tool provides an additional --diff-schema on the diesel migration generate command that allows to generate migrations based on the current schema definition and your database. To generate a migration equivalent to the shown Raw SQL migration you need to
> 
>     Create a schema.rs file with the following content:
> 
> schema.rs (PostgreSQL)
> [View on GitHub](https://github.com/diesel-rs/diesel/blob/2.2.x/examples/postgres/getting_started_step_1/src/schema.rs)
> 
> diesel::table! {
>     posts (id) {
>         id -> Int4,
>         title -> Varchar,
>         body -> Text,
>         published -> Bool,
>     }
> }
> 
> [The documentation of the table! macro](https://docs.diesel.rs/2.2.x/diesel/macro.table.html) contains the syntax used for this macros. [The diesel::sql_types module](https://docs.diesel.rs/2.2.x/diesel/sql_types/index.html) provides documentation for the SQL side types used to define the relevant columns.
> 
>     Run diesel migration generate --diff-schema create_posts
> 
> This will generate both the up.sql and the down.sql files of your migration pre-populated with the relevant SQL. After that, you should continue with the diesel migration run step.

which suggests to me that the statement

> We choose to generate those from your database schema, rather than generating your database schema from Rust declarations. You have to write one of those two, we chose the one which more precisely represents what you actually mean

is contradicting the documentation, especially the part

> generate your migrations based on Rust code

Now I understand that this issue is quite old so I'm taking this with a big grain of salt and would just like to have the confusion cleared up.

**Comment by weiznich** [comment]
@xdevs23 Old closed issues like this are the wrong place to ask support questions. Please use the discussion forum to ask you questions.
