### ISSUE TITLE
RunMigrationsError provides no information about the specific migration that failed

### ISSUE THREAD

**Issue by Aaron1011** [diesel-rs/diesel#1605]
While [RunMigrationsError](https://docs.rs/diesel_migrations/1.4.0/diesel_migrations/enum.RunMigrationsError.html) provides information about the type of migration error that occurred, it provides no information (e.g. the file path) about the specific migration that caused the error.

Since the `RunMigrationsError` enum has neither a `non_exhaustive` attribute nor a `#[doc(hidden)]` variant, adding new variants is a breaking change. It was suggested [on Gitter](https://gitter.im/diesel-rs/diesel?at=5abc1734e3d0b1ff2c7aeaaf) that a new error type (and corresponding functions) be created, and that the current `RunMigrationsError` and `run_migrations` be deprecated.

**Comment by sgrif** [comment]
Copying my comments from the gitter convo (and pinging the power rangers):

I can say with certainty that I intended to make that enum (and MigrationError) extensible, and it slipped through the cracks
(I wouldn't turn it into a struct, but that's semantics)
@diesel-rs/core I would like to get the rest of the core team's opinion here. I don't think there's anything we can do without a semver major version bump. I'm opposed to separating the version of diesel_migrations from the rest of the framework, and I'm also opposed to a semver-major bump on the whole shebang. That said, this enum should have been made extensible from the start. What do y'all think?

**Comment by Diggsey** [comment]
I think a couple of improvements could be made in the process: the names of some of the functions are a little odd (for example, the function to find all the migrations is called `mark_migrations_in_directory`) and a lot of the design seems to be quite heavily based on the implementation (for example, `name()` not being a method on the `Migration` trait, but a standalone function).

This would be a good opportunity to refactor some of this: for example creating a `MigrationSet` trait instead of passing around a raw `PathBuf`, which has methods to list `Migration`s.

**Comment by sgrif** [comment]
Yeah, a redesign was originally planned for 1.0 but we agreed that we could \ deprecate the current API backwards compatibly. That does not apply to types
