### ISSUE TITLE
Figure out a better way to deprecate old feature names

### ISSUE THREAD

**Issue by sgrif** [diesel-rs/diesel#1636]
The current way we're deprecating the various x-column-tables feature spams builds with an unreasonable number of warnings, and causes our crate to fail to compile if we have `#![deny(warnings)]`. Ideally we show the warning in the actual invocation of `table!`, but https://github.com/rust-lang/rust/issues/49912 prevents us from just doing the obvious thing there.

We should find a better solution though, that doesn't spam logs, and in particular, generates no warnings from inside Diesel itself when compiled with these features turned on. The solution of "remember to remove `#[deny(warnings)]` when we release isn't going to work long term.

**Comment by npapapietro** [comment]
What is the status of this with https://github.com/rust-lang/rust/pull/62042 fixing https://github.com/rust-lang/rust/issues/49912

**Comment by weiznich** [comment]
@npapapietro Yes those fix would help here. We are happy to receive a PR that fixes this. Based on the linked rustc issues it should be possible to just add a conditional `#[deprecated]` attribute to the `table!` macro. This can be done via `#[cfg_attr]` based on the deprecated feature flags (`large-table`, `huge-table`, ...)

**Comment by npapapietro** [comment]
I'll try and take this up. As I'm just diving into diesel I'd like some more info as this will be a 1st time pr. 

Let me see if if I understand this issue correctly

* You have a set of features that you would like to deprecate. Where does this list live? I see `with-deprecated` feature but it is an empty list at the moment.
* If diesel is build with one of these features we should add the `#[deprecated]` attr to the `table!` macro. Would this be injected into the `$meta` macro arg in `__diesel_parse_table` or at the `impl` of each feature case? This is where I am slightly confused.

**Comment by weiznich** [comment]
> You have a set of features that you would like to deprecate. Where does this list live? I see with-deprecated feature but it is an empty list at the moment.

We would like to deprecate the `huge-tables` feature in favor of the `64-column-tables` feature flag. Also the `large-tables` feature in favor of the `32-column-tables` feature. 

> If diesel is build with one of these features we should add the #[deprecated] attr to the table! macro. Would this be injected into the $meta macro arg in __diesel_parse_table or at the impl of each feature case? This is where I am slightly confused

Adding the deprecated attribute inside the expanded `table!` macro does not work, as code in those context does not have access to the corresponding flag. (That's because the expanded code is parsed in the context of a third party crate.) 
I propose that we just add the the `#[deprecated]` attribute on `table!` itself, so that the user gets the corresponding warning there. The deprecated attribute should be only conditionally enabled via `#[cfg_attr]`.

**Comment by weiznich** [comment]
Closed by #2968
