### ISSUE TITLE
Feature: support tables without a primary key

### ISSUE THREAD

**Issue by Diggsey** [diesel-rs/diesel#1661]
Pretty self explanatory - there's not really a reason to prevent inserting into a table without a primary key. Not supporting operations requiring `Identifiable` is fine.

**Comment by sgrif** [comment]
This isn't possible until Diesel 2.0. We may eventually try to generalize "data source" as a supertrait of `Table`, which has no primary key (e.g. views), but tables should always have some form of primary key.

**Comment by weiznich** [comment]
It will require a breaking change because we need do separate `Table` in such a way that there is a supertrait of `Table` that contains the `AllColumns` associated type and the `all_columns` function. The `Table` trait would than contain only the `PrimaryKey` associated type and the `primary_key` function. It is a breaking change because this would break all code that currently implements `Table`.

@sgrif Maybe we should introduce a diesel 2.0 tag to have a list of things we may want to fix in 2.0?

**Comment by Diggsey** [comment]
Not calling it a `Table` seems confusing - whether or not something has a primary key is incidental to whether it's a table.

I currently have a table which implements a "set" data structure - the "value" is not the primary key because for reasons relating to locking, it is preferable to allow transient duplicate items than to enforce uniqueness (which could cause "insert" operations to have to wait on "remove" transactions, which are slow).

**Comment by sgrif** [comment]
@Diggsey You can just tell Diesel some random column is the primary key

**Comment by KeenS** [comment]
Is this planned to be developed for diesel 2.0? (And is diesel 2.0 is planned?)

I want to use [partitioned tables](https://www.postgresql.org/docs/10/static/ddl-partitioning.html), which doesn't support primary key.

**Comment by KeenS** [comment]
I found diesel_cli supports table filtering.
https://github.com/diesel-rs/diesel/blob/master/diesel_cli/tests/print_schema/print_schema_except_tables/diesel.toml
I'm going to use it until diesel 2.0 get released

**Comment by MeKeyCool** [comment]
Hi ! Any news from diesel v2.0 ?
I am currently writing a table of events. I don't care id or any primary key. I even didn't interface anything in code.

But in my up.sql file i wrote :
```sql
CREATE TABLE task_status_history (
  task_id BIGINT NOT NULL REFERENCES tasks(id),
  status_id  INT NOT NULL REFERENCES task_status(id),
  author_id VARCHAR(36) NOT NULL,
  transition_timestamp TIMESTAMP NOT NULL
);
```
And when i run `diesel database reset`, i got `Diesel only supports tables with primary keys. Table task_status_history has no primary key` message

I am new in rust and with diesel but i just want a tool that manage db access and migrations.
If i can write my sql queries by hand with some custom arguments (/parameters) it would be perfect.

So, 
Should i wait for diesel v2.0 ? (sounds too long)
Am i wrong using diesel ?
Did i miss the proper way to use it ?

Maybe if the point is simple enough and i have some advices, i could help to solve the problem.

**Comment by MeKeyCool** [comment]
I just tested but i have the same problem with a join table (that doesn't need a primary key either)
```sql
CREATE TABLE task_teams (
  task_id BIGINT NOT NULL REFERENCES tasks(id),
  user_id VARCHAR(36) NOT NULL,
  team_role_id INT NOT NULL REFERENCES team_roles(id)
);
```

**Comment by weiznich** [comment]
@MeKeyCool In my opinion using tables without an primary key is normally am anti pattern that should be avoided. There ere specific narrow cases where this is required due to external constrains, but in general a table should have some (composite) primary key. For your example the natural primary key would just be a tuple of all three foreign keys. 

For cases where there cannot be a primary key due to implementation limitations or such things the workaround of filtering out such tables and then define them manually with an fake primary key works well enough in practice in my opinion.

As for the release date of diesel 2.0: We do not give any ETA's other then when it's done. This is a project run in our free time, so please consider that if you are asking for such things.

**Comment by jamessewell** [comment]
This seems like a big problem - what about timeseries data?

Just to clarify - what is the impact of giving diesel an incorrect primary key?

**Comment by weiznich** [comment]
@jamessewell Just repeating that you need some feature will not let it magically appear. If a specific feature is important to you, you should consider to start contributing something or find a other way to support people working on this feature. Otherwise this sounds like you request that other people do the work for free for you, which would just be rude. We are happy to receive a proposal how such the corresponding API would look like as feature request. (Checkout the contributors help for details about what is expected from a well written feature request)

That written: Our issue tracker is not the right place to ask questions about something. Please use the forum or the gitter channel for this.

**Comment by videni** [comment]
@jamessewell , did you find  other workaround?  I am also using this library with  timeseries data,  timescaledb.


```
CREATE TABLE IF NOT EXISTS "account_traffic" (
    account_id UUID NOT NULL,
    traffic integer NOT NULL DEFAULT '0',
    time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(time)
);
```

seems it's not right to set the time column as primary key,  because the time may be same.

**Comment by videni** [comment]
@jamessewell , did you find  other workaround?  I am also using this library with  timeseries data,  timescaledb.


```
CREATE TABLE IF NOT EXISTS "account_traffic" (
    account_id UUID NOT NULL,
    traffic integer NOT NULL DEFAULT '0',
    time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(time)
);
```

seems it's not right to set the time column as primary key,  because the time may be same.

**Comment by lukesneeringer** [comment]
> @jamessewell , did you find other workaround? I am also using this library with timeseries data, timescaledb.
> 
> ```
> CREATE TABLE IF NOT EXISTS "account_traffic" (
>     account_id UUID NOT NULL,
>     traffic integer NOT NULL DEFAULT '0',
>     time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
>     PRIMARY KEY(time)
> );
> ```
> 
> seems it's not right to set the time column as primary key, because the time may be same.

I have the exact same use case. I worked around this by creating the table, immediately dropping the primary key, and adding a new composite primary key. It seemed to trick Diesel. I expect I would have problems if I use the `find` function (not very far along yet), but I can plan not to do this.
