### ISSUE TITLE
Unable to build with latest nightly version.

### ISSUE THREAD

**Issue by brizental** [diesel-rs/diesel#1754]
### Versions

- **Rust:** nightly-2018-06-05
- **Diesel:** 1.3.0
- **Database:** mysql
- **Operating System** macos

### Feature Flags

- **diesel:** mysql, r2d2

## Problem Description

Can't build with latest nightly version.

### What are you trying to accomplish?

Build.

### What is the expected output?

No errors.

### What is the actual output?

```
error[E0277]: the trait bound `<expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Add` is not satisfied
  --> /Users/brizental/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.3.0/src/expression/count.rs:58:39
   |
58 | #[derive(Debug, Clone, Copy, QueryId, DieselNumericOps)]
   |                                       ^^^^^^^^^^^^^^^^ the trait `sql_types::ops::Add` is not implemented for `<expression::count::CountStar as expression::Expression>::SqlType`
   |
   = help: consider adding a `where <expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Add` bound
   = help: see issue #48214
   = help: add #![feature(trivial_bounds)] to the crate attributes to enable

error[E0277]: the trait bound `<expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Sub` is not satisfied
  --> /Users/brizental/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.3.0/src/expression/count.rs:58:39
   |
58 | #[derive(Debug, Clone, Copy, QueryId, DieselNumericOps)]
   |                                       ^^^^^^^^^^^^^^^^ the trait `sql_types::ops::Sub` is not implemented for `<expression::count::CountStar as expression::Expression>::SqlType`
   |
   = help: consider adding a `where <expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Sub` bound
   = help: see issue #48214
   = help: add #![feature(trivial_bounds)] to the crate attributes to enable

error[E0277]: the trait bound `<expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Mul` is not satisfied
  --> /Users/brizental/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.3.0/src/expression/count.rs:58:39
   |
58 | #[derive(Debug, Clone, Copy, QueryId, DieselNumericOps)]
   |                                       ^^^^^^^^^^^^^^^^ the trait `sql_types::ops::Mul` is not implemented for `<expression::count::CountStar as expression::Expression>::SqlType`
   |
   = help: consider adding a `where <expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Mul` bound
   = help: see issue #48214
   = help: add #![feature(trivial_bounds)] to the crate attributes to enable

error[E0277]: the trait bound `<expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Div` is not satisfied
  --> /Users/brizental/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.3.0/src/expression/count.rs:58:39
   |
58 | #[derive(Debug, Clone, Copy, QueryId, DieselNumericOps)]
   |                                       ^^^^^^^^^^^^^^^^ the trait `sql_types::ops::Div` is not implemented for `<expression::count::CountStar as expression::Expression>::SqlType`
   |
   = help: consider adding a `where <expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Div` bound
   = help: see issue #48214
   = help: add #![feature(trivial_bounds)] to the crate attributes to enable
```

### Steps to reproduce

Try to build something with the latest nightly version.

**Comment by gwihlidal** [comment]
I'm having this same problem now too

**Comment by weiznich** [comment]
It's a rustc bug, see #1700 #1701 #1705 #1711 #1729 , #1730 , #1731, #1737 , rust-lang/rust#50825 and rust-lang/rust#51042

**Comment by mathroc** [comment]
@weiznich it might be interesting to keep one of these issue open until this is resolved. it would avoid people opening the same issue again and again . and give them an issue to subscribe to to be notified when this is resolved

I guess this is not something that can be solved on diesel side but it's still a in issue to its usage worth tracking imho (eg: I'm waiting for this to upgrade some dependencies that require a newer rustc because there is no rustc version that works with the newer version of those libs and diesel)

**Comment by weiznich** [comment]
@mathroc The issue is fixed since the [8 of June](https://github.com/rust-lang/rust/pull/51042#issuecomment-395803768).

> it might be interesting to keep one of these issue open until this is resolved. it would avoid people opening the same issue again and again .and give them an issue to subscribe to to be notified when this is resolved

The issue was closed because of several reasons:
* It is nothing that is actionable for the diesel team. Our policy is than only actionable issues should be open. All other issues are closed. (This does not mean we do not response to questions ask in closed issues, it just means that we categorize issues in a certain way)
* It is a bug in rustc so the bugreport does not belong to the diesel repo, but to the rustc repo. To have a issue to subscribe to people should go there because the issue will be fixed there.
