### ISSUE TITLE
src/lib.rs from getting started guide is different from github source.

### ISSUE THREAD

**Issue by Qwertie-** [diesel-rs/diesel#1758]
On the [getting started guide](http://diesel.rs/guides/getting-started/)
the use section of src/lib.rs contains
```
use diesel::prelude::*;
use diesel::pg::PgConnection;
use dotenv::dotenv;
use std::env;
```

but in the [github source](https://github.com/diesel-rs/diesel/blob/v1.3.0/examples/postgres/getting_started_step_1/src/lib.rs#L8) it contains 

```
use diesel::prelude::*;
use dotenv::dotenv;
use std::env;

```

**Comment by weiznich** [comment]
Both are equivalent because `diesel::prelude` exports `PgConnection` if the as soon as the postgres feature is enabled.
That said it would be great to fix this inconsistency. If you (or somebody else) is interested to open a PR: The source for the web page [is here](https://github.com/sgrif/diesel.rs-website/blob/master/source/views/guides/getting-started.html.slim#L226)
