### ISSUE TITLE
SQLite: on_conflict().do_udpate() support

### ISSUE THREAD

**Issue by theduke** [diesel-rs/diesel#1854]
SQLite supports full UPSERT functionality equivalent to Postgres now.

Like: `INSERT INTO phonebook(name,phonenumber) VALUES('Alice','704-555-1212')
  ON CONFLICT(name) DO UPDATE SET phonenumber=excluded.phonenumber;`

See: https://www.sqlite.org/lang_UPSERT.html

Would be really great to support this, the same way it works in PG:

```rust
value.insert_into(table)
  .on_conflict(id)
  .do_update()
  .set(...)
```

**Comment by sgrif** [comment]
Thank you for the feature request. We're currently in the process of a cleanup of the issue tracker, and aren't currently accepting feature requests (there will be an official policy written soon, but the TL;DR is that open issues should reflect something that is a bug or on our immediate roadmap).

We're happy to discuss feature requests, but the place to do so is discourse.diesel.rs, not the issue tracker.

**Comment by theduke** [comment]
Understood.
The README should reflect this new policy, though.

Would you still accept PRs for new features though?

**Comment by sgrif** [comment]
> there will be an official policy written soon

Thanks for your patience.

**Comment by theduke** [comment]
Guess I missed that ;).

**Comment by sgrif** [comment]
I'm actually going to re-open this, since I think implementing it will be fairly easy and would be a nice addition for 1.4

**Comment by sgrif** [comment]
Go for it

**Comment by h-michael** [comment]
@sgrif
Thanks to your reply.
BTW, both of Postgress and Sqlite have same query syntax for upsert.
How do you think how to pg and sqlite share query builder mdule?
If you have any ideas, please tell me your thought.
postgres https://www.postgresql.org/docs/10/static/sql-insert.html
sqlite https://www.sqlite.org/lang_UPSERT.html

**Comment by weiznich** [comment]
There is already an implementation of ` on_conflict().do_update()` for postgresql [here](https://github.com/diesel-rs/diesel/tree/master/diesel/src/pg/upsert).

What needs to be done:
* Move that module to `diesel::upsert` and add reeports at the current location (otherwise this is a breaking change). Also make this module only available if the `sqlite` or `postgres` feature is given.
* See what parts are available on both systems, all other parts should be moved back to the postgres specific module.
* Add a new trait `SupportsOnConflictClause` and implement it for `Pg` and `Sqlite`. (Similar to `SupportsReturningClause` [here](https://github.com/diesel-rs/diesel/blob/master/diesel/src/backend.rs#L56))
* For all `QueryFragment<Pg>` impl's left in the new `diesel::upsert` module, change them to be `impl<DB> QueryFragment<DB> for … where DB: SupportsOnConflictClause`
* Look for `upsert` test that apply for both backends and enable them on `sqlite`. (For example [this one](https://github.com/diesel-rs/diesel/blob/master/diesel_tests/tests/update.rs#L230))

Feel free to open a PR early in that progress to get feedback there. Also ask in our gitter channel if you get stuck somewhere.

**Comment by h-michael** [comment]
@weiznich
Thanks to your advide.
I'll implement this weekend!

**Comment by weiznich** [comment]
Closed by #1884

**Comment by Ciantic** [comment]
Hmm, was this implemented? I can't find as single example with SQLite and insert with `on_conflict` from here: https://github.com/diesel-rs/diesel/blob/master/examples/sqlite/all_about_inserts/src/lib.rs

Also my testing suggests `on_conflict` is not defined when using SQLite.

**Comment by weiznich** [comment]
@Ciantic You can see at the merged PR that this is implemented, but not released yet. Therefor its expected that you get this error message.

**Comment by bivald** [comment]
@Ciantic If you need it right now, you can use the GIT as a source for cargo:

```
diesel_migrations = { version = "^2.0.0", git = "https://github.com/diesel-rs/diesel/"}
diesel = { version = "^2.0.0", features = ["sqlite", "uuid", "chrono"], git = "https://github.com/diesel-rs/diesel" }
```

Cargo will magically find diesel_migrations on git (which I thought was pretty awesome)

I've implemented UPSERT for SQLite in my project last night and it works beautifully :)

```
    let result = diesel::insert_into(schema::alias::table)
        .values(&new_alias)
        .on_conflict(schema::alias::id)
        .do_update()
        .set(&new_alias)
        .execute(connection);
```

To get 2.0.0 working I had to:
1. Update diesel migrate (see https://github.com/diesel-rs/diesel/blob/master/CHANGELOG.md#diesel_migration-rewrite)
2. Add `AsChangeset` to my `Insertable`:

```
#[derive(Insertable, AsChangeset)]
```
