### ISSUE TITLE
Support mysql's CLIENT_FOUND_ROWS flag

### ISSUE THREAD

**Issue by pjenvey** [diesel-rs/diesel#1868]
This is a common flag to enable w/ mysql's unusual default behavior of returning the number of rows actually changed during an UPDATE (vs how many were matched). 

Some ORMs even default this flag to on for more consistency across dialects (e.g. [sqlalchemy](https://docs.sqlalchemy.org/en/latest/dialects/mysql.html#rowcount-support) and [activerecord](https://github.com/rails/rails/blob/aa3dcab/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L16)).

**Comment by blackghost1987** [comment]
Thanks, this was bugging me for a while! This silly default behavior of MySQL can be really surprising when changing Diesel backends.

I think the relevant code is the last parameter of the `ffi::mysql_real_connect` call in `RawConnection::connect()`.
The big problem here is that Client Flags can't be encoded in the URL as it seems 😞 So we either put it in as a default, or we have to modify the public API (not just for MySql) to somehow pass these flags to a `Connection`.

The easiest way would be to make it a default, but I'm worried this would be a breaking change for some applications, maybe somebody is taking advantage of this behavior. I'm not saying it can't be done, but it probably requires a major version release?

I couldn't find a way to make this configurable, but here are the steps I came up with, maybe somebody better versed in Diesel could take a look and finish this plan:
1. create a bitflag for MySql Capability Flags as per https://dev.mysql.com/doc/internals/en/capability-flags.html
2. add the bitflag to `mysql::connection::ConnectionOptions` (make it optional, because it can't be parsed from the URL, so it had to be set later on)
3. use the bitflag in `RawConnection::connect()` as the mysql_real_connect() call's last parameter
4. create a way to somehow modify the `ConnectionOptions` instance AFTER parsing the URL but BEFORE calling `connect()`

The last part is the real catch here, because `ConnectionOptions::parse()` and `raw_connection.connect()` are both done in `establish(database_url: &str)`, which is defined in the `Connect` trait. So we can't add a parameter to `establish()` without adding it to every backend. Also it's a static constructor, so we cannot set a value in the instance previously either....

Any more ideas?

**Comment by weiznich** [comment]
@blackghost1987 would be fine with setting this flag by default. Feel free to open a PR for this against the master branch.

**Comment by blackghost1987** [comment]
@weiznich thanks for merging the PR into master! This issue probably should be closed as well
