### ISSUE TITLE
Connection with dynamic backend based on connection string

### ISSUE THREAD

**Issue by guangie88** [diesel-rs/diesel#1881]
Are there any plans to support `Connection` that can switch to any of the supported database connections at runtime? Might look something like the following in [Python SQLAlchemy](https://docs.sqlalchemy.org/en/latest/core/engines.html#sqlalchemy.create_engine). `Connection` trait object doesn't work due to trait object safety.

It would be useful for code that can dynamically change the connection backend based on the connection string.

**Comment by weiznich** [comment]
That's more or less out of scope for diesel, because diesel depends on compile time on knowing what database is used and then generates the corresponding sql specific to that database. 
Also it will prevent using unsupported sql features at compile time. (For example you could only use `Unsigned<Integer>` using the `MySql` backend. For all other connections/backends this results in a compiler error. Adding a generic connection type would result in one of the two following strategies:
* Support only a common subset of sql that is supported on all backends (if that even exists and if it's usefull)
* Possibility to generate sql that is invalid (We should not do that, in my opinion.)


(Closed because this is nothing directly actionable for the diesel team. Use [our discourse forum](http://discourse.diesel.rs) for feature requests.)
