### ISSUE TITLE
Early warning for missing client libraries

### ISSUE THREAD

**Issue by levkk** [diesel-rs/diesel#1893]
### Versions

- **Rust:** 1.31.0-nightly (just because I'm also using Rocket)
- **Diesel:** 1.3.3
- **Database:** PostgreSQL
- **Operating System** Ubuntu 18.04

## Problem Description

Early detection of missing client libraries. It would be nice for the diesel CLI installation to detect the missing libraries (i.e. libpq) before the compilation starts. It takes a bit of time to compile and seeing the error only at the end is a bit frustrating :)

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
Unfortunately, this isn't really something we have any control over. It's entirely dependent on your system setup and your linker, which Diesel doesn't interact with at all. It might be worth writing an RFC to add this sort of capability to rustc/cargo. I agree it'd be great to improve this, but it's just not possible today. Since there's nothing actionable here, I'm going to close this issue.
