### ISSUE TITLE
Probably related to diesel -> Weird Rust / Hyper / Async behaviour. Why ??

### ISSUE THREAD

**Issue by goriunov** [diesel-rs/diesel#1906]
### Versions

- **Rust:** 1.30
- **Diesel:** latest
- **Database:** PG 10
- **Operating System** Arch linux

### Feature Flags

- **diesel:** PG r2d2

## Problem Description
https://www.reddit.com/r/rust/comments/9ulbj3/weird_rust_hyper_async_behaviour_why/

Video shows everything, i have run multiple times and have gotten that this happens mostly on `diesel::insert_into` execution.

### Steps to reproduce
Check out my repo  https://github.com/goriunov/rust-test you can find a comment in code in main.rs

```rust
      // uncomment next line to speed up everything
      // println!("Print me");
```

try running with and without `println!("Print me");` line and then bench mark with wrk for example 

```
wrk -t1 -c100 -d10s --latency http://127.0.0.1:3000
```

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

Thank you very much :)

**Comment by sgrif** [comment]
It looks like a lot of folks have already commented with ideas. Ultimately if the difference in performance is a `println!`, this is not something that is related to Diesel. Outside of "looks like maybe a compiler bug", there's not much insight I can offer you. However, Diesel does not interact with stdout in any way, so if the addition/removal of a `println!` is what changes your performance characteristics, Diesel is not the root cause.
