### ISSUE TITLE
Allowing sqlite unsigned

### ISSUE THREAD

**Issue by 0xpr03** [diesel-rs/diesel#1907]
### Versions

- **Rust:** 1.29.2
- **Diesel:** 1.3.3
- **Database:** sqlite
- **Operating System** linux
## Problem Description
I can't describe unsigned integers in diesel for sqlite, although I'm trying to access an existing DB with unsigned integer. (Called integerunsigned by SQliteBrowser)

### What are you trying to accomplish?
Access unsigned integers in sqlite.

### Steps to reproduce
db.rs:
```rust
let connection =
            SqliteConnection::establish("mydb.db").expect("Csn't rach db");
        let result = General
            .load::<GeneralEntry>(&connection)
            .expect("Can't query db settings");
```

schema.rs:
```rust
table! {
    General(key) {
        key -> VarChar,
        timestamp -> Unsigned<Integer>,
        value -> VarChar,
    }
}

```
models.rs:
```rust
use schema::General;

#[derive(Queryable)]
pub struct GeneralEntry {
    pub timestamp: u32,
    pub key: String,
    pub value: String,
}

#[derive(Insertable)]
#[table_name = "General"]
pub struct NewGeneral<'a> {
    pub timestamp: u32,
    pub key: &'a str,
    pub value: &'a str,
}

```

Output rustc:
```log
.load::<GeneralEntry>(&connection)
    |              ^^^^ the trait `diesel::sql_types::HasSqlType<diesel::sql_types::Unsigned<diesel::sql_types::Integer>>` is not implemented for `diesel::sqlite::Sqlite`
```

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by 0xpr03** [comment]
I'm not fully sure whether this is a standard, but at least the DB I use has a "integerunsigned" field and the sqlite browser I use seems to find this normal ?

**Comment by weiznich** [comment]
Sqlite does not support unsigned integers. That's "just" sqlites strange type system that accepts nearly everything as type name. Internally sqlite has only 5 types: `Null`, `Integer`, `Real`, `Text` and `Blob`. Each type name is mapped to one of the supported types. There are multiple rules for determining the resulting type from the given type name. In your case the following rule applies
> If the declared type contains the string "INT" then it is assigned INTEGER affinity.

to `intergerunsigned`, so just `Integer` is used as type.

See [the sqlite documentation](https://www.sqlite.org/datatype3.html) for more details.


Diesel won't change the current behaviour because we try to represent the underlying database technical correctly.

**Comment by 0xpr03** [comment]
Ah thanks, that explains my confusion when I tried to look up uInt in the sqlite docs. I guess that's what you get for trying to read 3rd party sqlite DBs.
