### ISSUE TITLE
Order by a calculated value.

### ISSUE THREAD

**Issue by sbwtw** [diesel-rs/diesel#1908]
I want select some items order by the relative timestamp, the sql like this:
`select title, time from articles order by ABS(time - TIMESTAMP('2018-01-01')) asc limit 10;`
it's works in mysql but I don't know how to do in diesel (without hard code raw sql).

**Comment by weiznich** [comment]
Have you tried to pass that expression to `order_by`? (That may require to define some functions using `sql_function!` in this case.)


I will close this issue because this is nothing actionable for the diesel team. Please use our [gitter channel](https://gitter.im/diesel-rs/diesel) or our [forum](https://discourse.diesel.rs/) to ask questions.
