### ISSUE TITLE
Redshift Support

### ISSUE THREAD

**Issue by davidarmstronglewis** [diesel-rs/diesel#1986]
I feel like this is shot in the dark, since Redshift is closed-source. But I would really love to use Diesel on the project I am on right now, where we use Redshift. Up to now I've been using sfackler's fantastic rust-postgres, but I would really appreciate a solid ORM like Diesel, so I figured I would propose it.

Redshift is based on Postgres 8.0.2, but surely has deviated quite a bit - however the query syntax is still the same. Certain things do not work that prevent me from going too far, such as the autogenerated diesel_setup migration. I don't see any other issues open or closed for this topic so I assume it just hasn't been brought up.

Thank you for taking the time, I appreciate you all :)

**Comment by weiznich** [comment]
That will require a custom connection/backend implementation. Our current policy about that is that we will not add a new backend to diesel itself because it is possible to do that outside of diesel (at least with some nightly features).

That said: It is currently not possible to change the code used to setup the migration table. That will change for diesel 2.0. See #1676 for a possible implementation.

I'm closing this issue because there is nothing actionable for diesel here. The migration thing is already tracked with that PR. If you need any help with the custom backend implementation just ping someone on [gitter](https://gitter.im/diesel-rs/diesel/) or open a thread in our [discourse forum](https://discourse.diesel.rs).

**Comment by davidarmstronglewis** [comment]
@weiznich okay, that makes a lot of sense. I'm sorry that it's not currently possible - I'll look into the custom backend implementation option, but I'm not sure I could make that fly on my project due to a lack of expertise on my end and a lack of community support if I were to build such a thing. Thank you for the reference to #1676, I'll check that out.

Cheers
