### ISSUE TITLE
lack of Expression on i64 and with tht joinable! on primary keys i64 fails (schema generated ocrrectly)

### ISSUE THREAD

**Issue by przygienda** [diesel-rs/diesel#1994]
### Versions

- **Rust:** 1.32 stable
- **Diesel:** diesel = { version = "1.4.0"
- **Database:** postgree 
- **Operating System**

### Feature Flags

- **diesel:** features = ["postgres", "serde_json", "chrono", "r2d2"] }

## Problem Description

Expression for i64 not implemented, with that no primary keys BigInt possible 

### What are you trying to accomplish?

primary keys BigInt necessary, i64 on schema generated, joinable! fails

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by kiljacken** [comment]
FWIW, I'm using a bigint primary key for a table, and I've encountered no issues so far. Perhaps you could provide a code sample and the `cargo check`output? :)

**Comment by sgrif** [comment]
Unfortunately, without steps to reproduce there's nothing we can do to help. If you're still having this problem, please open a new issue with information we can use to reproduce your problem. A small code sample that demonstrates the issue would be most helpful.

**Comment by Justice4Joffrey** [comment]
I sometimes get got by this when the SQL table definition is incorrectly using `INTEGER` rather than `BIGINT` and I want an `i64`, and presumably other forms of subtle mismatching.

It's clearly an error on my side, but often takes a bit of headscratching time. A more descriptive error from the macro (or even a generic "check the table definition matches your structs") could be very helpful.

**Comment by weiznich** [comment]
@Justice4Joffrey That's not the right place for such comments. This issue is closed due to missing information + not really related to what you describe. If you have concrete suggestions how to improve something please open up a new [idea discussion](https://github.com/diesel-rs/diesel/discussions/new?category=ideas) thread. For general discussion use the [q&a discussion section](https://github.com/diesel-rs/diesel/discussions/new?category=q-a).
