### ISSUE TITLE
Consider allowing empty changeset

### ISSUE THREAD

**Issue by torkleyy** [diesel-rs/diesel#1996]
Is there any reason that Diesel returns an error when trying to apply an empty changeset?

Example:

```rust
#[derive(AsChangeset, Clone, Debug, Default, Eq, Hash, PartialEq)]
#[table_name = "users"]
pub struct ChangeUser<'a> {
    pub address: Option<&'a str>,
    pub name: Option<&'a str>,
}

// This errors because there are no changes to execute
diesel::update(users::table.find(1)).set(&ChangeUser::default()).execute(&connection).unwrap();
```

Would it make sense to just return `Ok(0)` in this case?

**Comment by sgrif** [comment]
> Is there any reason that Diesel returns an error when trying to apply an empty changeset?

Because there's no obviously correct thing to do here. We could generate some valid SQL that does nothing (e.g. `SET id = table.id`), but that would cause triggers to fire which may not be expected. `Ok(0)` isn't clearly the correct thing to do either, since that number is how many rows were matched, regardless of if the changes requested actually affected anything.

Even if we wanted to return `Ok(0)` here, doing so would be rather challenging since the place this error is generated has to return `Result<(), Box<std::error::Error>>`, so handling this at the connection level would be extremely difficult.

The current behavior was introduced in https://github.com/diesel-rs/diesel/commit/579c6934 if you're interested in a little more context.

**Comment by torkleyy** [comment]
Okay, thank you for the thorough explanation!
