### ISSUE TITLE
the trait `diesel::sql_types::SqlOrd` is not implemented for `diesel::sql_types::Datetime

### ISSUE THREAD

**Issue by johnkarasev** [diesel-rs/diesel#2021]
I am trying to find all entries that have the max datetime but I get SqlOrd not implemented error. 

```shell
error[E0277]: the trait bound `diesel::sql_types::Datetime: diesel::sql_types::SqlOrd` is not satisfied
  --> src/db/routes/demand.rs:17:68
   |
17 |             .filter(powerf::forecast_date.any(powerf::table.select(max(powerf::forecast_date))))
   |                                                                    ^^^ the trait `diesel::sql_types::SqlOrd` is not implemented for `diesel::sql_types::Datetime`
```

**Comment by weiznich** [comment]
Already fixed by #2013

**Comment by RalfNorthman** [comment]
Got this error today on 1.4.6. It would be nice to have this feature in an official release.

**Comment by weiznich** [comment]
@RalfNorthman Requesting that a certain feature is included in a patch release will not get this feature released any sooner. Our next feature release will contain this feature. If you want to make this happen sooner consider contributing something to the open issues listed in the diesel 2.0 milestone, otherwise stop requesting releases containing specific features.
