### ISSUE TITLE
Get raw result without structuring

### ISSUE THREAD

**Issue by mikhail-krainik** [diesel-rs/diesel#2022]
### Versions

- **Rust:**
rustc 1.35.0-nightly
- **Diesel:**
diesel 1.3.0
- **Database:**
PostgreSQL 10
- **Operating System**
Ubuntu
### Feature Flags
["postgres", "r2d2", "chrono"]
- **diesel:**

## Problem Description

I want to receive data from a database with a flexible response structure. I do not have a specific structure for each response from the database. My requests are formed through a set of stackable conditions and the result of the request can be each query unique, so I can’t fit it into any response structure but I should to that
```rust
let data = query.load::<_>(&connection)?;
```
### What are you trying to achieve?
I want to get the raw response data from the database, in which I can generate json, hashmap (key, value) or any other flexible structure, I do not know how many columns contain the answer

### What is the expected output?
Array of rows and columns

### What is the actual output?
I should set type for query result

### Example
``` rust
let mut query = users::table
            .left_join(profile::table)
            .left_join(posts::table)
            .left_join(notes::table)
            .left_join(bookmarks::table)
            .into_boxed();
if !filter.is_empty() {
    query = query.filter(sql(" ").bind::<Text, _>(filter))
}

if !select.is_empty() {
    query = query.select(sql(" ").bind::<Text, _>(select))
}

if !group.is_empty() {
   query = query.filter(sql("GROUP BY ").bind::<Text, _>(group));
}

let result = query.load(connection)
```

**Comment by weiznich** [comment]
A few random thoughts:

* Something like your example does already compile, but will result in a syntax error. That will never change no matter what we change on diesel itself, because you explicitly bind some raw strings. That means the database interprets those things as strings and not as sql fragment. For example your select clause will boil down to something like `select 'your select string' from …` which means you select a constant string.
* For the filter part that's already there. Take a look on [`BoxableSelectStatements`](http://docs.diesel.rs/diesel/query_dsl/trait.QueryDsl.html#method.into_boxed) and [`BoxableExpressions`](http://docs.diesel.rs/diesel/expression/trait.BoxableExpression.html)
* For the other parts: I would like to see a concrete proposal how such an API could look like. Would you mind posting a proposal to our [discourse instance](https://discourse.diesel.rs/)?

**Comment by mikhail-krainik** [comment]
You right there was some syntax error I made synthetic example

**Comment by mikhail-krainik** [comment]
moved question to https://discourse.diesel.rs/t/get-raw-result-without-structuring/80
