### ISSUE TITLE
This Application Was Unable to Start Correctly (0xc000007b)

### ISSUE THREAD

**Issue by JordiOfRivia** [diesel-rs/diesel#2034]
Hey all,

I installed diesel correctly. 
And diesel worked for a while.
But now every time  when  i run run a diesel command i get the following error message:
"This Application Was Unable to Start Correctly (0xc000007b)"
I already tried all the solution on the internet.
But that doesn't seem to work.

Error:
https://gyazo.com/416561f6cbe65c79fc623416f0216c74

Can somebody help me with my problem?

**Comment by weiznich** [comment]
This means windows is missing some dll that was available at linking time. I'm not sure how you make windows aware of the required dll's, maybe by just adding them to the PATH or copying them to the same directory as `diesel.exe`?

**Comment by Wolfman13** [comment]
Did you ever manage to find out which DLLs were missing?

**Comment by weiznich** [comment]
@Wolfman13 Our issue tracker is not the right place to ask such questions. Please use the forum or the gitter chat for such questions.

**Comment by andrewbanchich** [comment]
Why is the issue tracker the wrong place for this? This is evidently a problem multiple users of Diesel have experienced, and the first place people go is GitHub Issues. If someone already solved the problem, they should post the answer here so others can see the solution without making them join a Discord / Discuss whatever.

They also didn't even ask the maintainers of Diesel for anything, so I'm not sure how communication between @Wolfman13 and @JordiOfRivia is even a problem for you.

**Comment by weiznich** [comment]
@andrewbanchich Please stop adding comments here. Our Contribution Guidelines and the issue template clearly suggest that our issue tracker is a place for the contributor team to track issues, not to provide support for broken system configurations.
If you want to ask questions about such problems feel free to use some other support channel for this.

**Comment by DRKSLV** [comment]
My process (successfully) troubleshooting the diesel installation::

I had several problems with dlls:
- First i had to copy libpg.lib from Postgres' files into the rust library folder (very unintuitive)
 (Instructions: https://github.com/diesel-rs/diesel/issues/487#issuecomment-654568069)
- Then i had the problem that "libintl-8.dll" couldn't be found
 It was a MinGw dll, but somehow my installation didn't have the file.
- I got another distribution of MinGw, which claimed to be "for 32bit and 64bit systems"
- The 0xc000007b error came up, which doesn't mean "dll missing", it means "program loaded 64 and 32 bit dlls at the same time" - turns out, the MinGw installation was in 32bit, which is bad
- I reinstalled MinGw from here: https://winlibs.com/
 Seems to be the most overkill version out there, it's 1.13 GB large... but yk diesel is working now, finally

Hope this can help someone figure this out faster in the future
Its a bit of a pain
