### ISSUE TITLE
eq(any()) won't compile with composite key

### ISSUE THREAD

**Issue by toreskogp** [diesel-rs/diesel#2045]
### Versions

- **Rust:** 1.34
- **Diesel:** 1.4.2
- **Database:** Postgres
- **Operating System** Docker rust:1.34 (Debian-stretch)

### Feature Flags

- **diesel:** postgres, r2d2, uuid, chrono

### What are you trying to accomplish?
I am trying to use `eq(any())` to filter a query with a composite key, but it won't compile. Changing to `eq_any()` seems to solve the problem.

### What is the expected output?
The code should compile.

### What is the actual output?
The code won't compile and throws this error:
```
the trait `diesel::serialize::ToSql<diesel::sql_types::Record<(diesel::sql_types::Uuid, diesel::sql_types::Uuid)>, diesel::pg::Pg>` is not implemented for `(uuid::Uuid, uuid::Uuid)`
```

### Steps to reproduce
Filter a query with a compsite key using `eq(any())`. Changing `eq(any())` to `eq_any()` however seems to solve the problem.
```
let ids: Vec<(Uuid,Uuid)> = vec![...];

(user_role::user_id, user_role::role_id)
    .into_sql::<Record<_>>()
    .eq(any(ids))
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by sgrif** [comment]
This is intentional. eq(any()) is meant to specifically use a single bind param (as an array) for efficiency and prepared statement reuse. We cannot send a pg tuple as a single bind param (due to restrictions in pg), and therefore cannot send an array of tuples either. Each element must be it's own bind param, which defeats the purpose of eq(any ()) in the first place
