### ISSUE TITLE
cannot find type `Timetz` in this scope

### ISSUE THREAD

**Issue by makmm** [diesel-rs/diesel#2128]
### Versions

- **Rust:** `rustc 1.38.0-nightly (c43753f91 2019-07-26)`
- **Diesel:** `1.3.2`
- **Database:** PostgreSQL
- **Operating System** Debian sid chroot inside ChromeOS (crouton)

### Feature Flags

- **diesel:** `["postgres", "r2d2", "chrono"]`

## Problem Description

Adding a field with `TIME with time zone` causes an invalid schema.

### What are you trying to accomplish?

Build my code with a schema generated from a `TIME with time zone` field.

### What is the expected output?

-> no error

### What is the actual output?
```
error[E0412]: cannot find type `Timetz` in this scope
  --> src/schema.rs:36:17
   |
36 |         time -> Timetz,
   |                 ^^^^^^ help: a struct with a similar name exists: `Time`
```

### Are you seeing any additional errors?
yes, but they are unrelated

### Steps to reproduce

add a migration that creates a table with a TIME with time zone column.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
I'm not able to test this because my project cannot run on stable. I don't think it would change anything though.

**Comment by weiznich** [comment]
That type is currently not supported by diesel. It seems like that `chrono` does not provide a time zone aware time type (only a date time type, but that is something different, if you want to use that use `Datetime with time zone ` as sql type in that case). Therefore I see not much sense in adding those type definition to diesel itself. (It would be contra productive, because in that way third party crates could only provide implementations for their own types. By defining their own sql type (`Timetz` in that case) they could implement the corresponding traits for types from other crates.)


That said you can provide your own implementation similar to [this test case](https://github.com/diesel-rs/diesel/blob/master/diesel_tests/tests/custom_types.rs#L9-L47)

**Comment by makmm** [comment]
:(
