### ISSUE TITLE
Need installation steps of installing diesel_cli with mysql on windows gnu

### ISSUE THREAD

**Issue by fengyc** [diesel-rs/diesel#2138]
It needs some extra steps to install diesel_cli with mysql on windows stable-gnu (msys2 / mingw), might be helpful.

First , change the default toolchain:
```
cargo install stable-gnu
cargo default stable-gnu
```
Install the libmariadbclient in msys2/mingw
```
pacman -Syu
pacman -Ss mingw64/mingw-w64-x86_64-libmariadbclient
```
But the pkg-config file is missing, need to create one `/mingw64/lib/pkgconfig/mysql.pc` (copy from `sqlite3.pc`)
```
# Package Information for pkg-config

prefix=/mingw64
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: MySQL
Description: MySQL database engine
Version: 2.3.7-1
Libs: -L${libdir} -lmysqlclient
Libs.private: -lz
Cflags: -I${includedir}
```
Without the `mysql.pc` file,  `cargo install diesel_cli --no-default-features --features mysql` report that ` ld: cannot find -lmysql`.

**Comment by weiznich** [comment]
We cannot maintain installation steps for each dependency on each possible platform, therefore we only mention which libraries are required and don't document how they are installed somewhere. (In my personal opinion that should be part of the documentation of this dependencies, so of libmariadbclient in this case.)

I close this issue because that's nothing actionable for the diesel team.
