### ISSUE TITLE
Unexpected null for non-null column

### ISSUE THREAD

**Issue by SephVelut** [diesel-rs/diesel#2141]
```
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR NOT NULL,
    password VARCHAR NOT NULL
);

CREATE TABLE tracks (
    id      SERIAL PRIMARY KEY,
    path    VARCHAR NOT NULL,
    status  VARCHAR NOT NULL,
    user	SERIAL,
    FOREIGN KEY(user) REFERENCES users
);
```

Running `diesel migration run` results in `Unexpected null for non-null column`

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

Sqlite3. Stable rust channel. Diesel = "*" in the toml.

**Comment by CodesInChaos** [comment]
Caused by https://github.com/diesel-rs/diesel/issues/1535

The workaround is mentioning the referenced columns on the target table explicitly.

broken:

    FOREIGN KEY(user) REFERENCES users

working

    FOREIGN KEY(user) REFERENCES users(id)

*When searching for the problem it took me much longer to find the linked issue than finding this issue. So posting here in case somebody else has the same search patterns.*
