### ISSUE TITLE
sqlite: Queryable struct field order can silently swap columns

### ISSUE THREAD

**Issue by kpcyrd** [diesel-rs/diesel#2169]
### Versions

- **Diesel:** 1.4.2
- **Database:** sqlite

## Problem Description

I've noticed a bug in my program that, after some debugging, turned out to be due to diesel assigning a column to the wrong field. I've resolved this issue by checking the order of the sqlite columns and defining my struct fields in the exact same order.

I think this issue should be detected both at compile time (the expected database schema is known to generate `src/schema.rs`) and at runtime in case a certain combination of database migrations/rollbacks messes up the order.

### Steps to reproduce

- create a table and a `Queryable struct`
- make all fields/columns of the same type
- define the struct fields in a different order than the sqlite table (`a, b, c` and `a, c, b`)
- insert a row and query it
- notice that the value of the `c` column is in the `b` field and vice versa.

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
That's [documented behaviour](http://docs.diesel.rs/diesel/deserialize/trait.Queryable.html#deriving).

> When this trait is derived, it will assume that the order of fields on your struct match the order of the fields in the query. This means that field order is significant if you are using #[derive(Queryable)]. Field name has no effect.

> I think this issue should be detected both at compile time (the expected database schema is known to generate src/schema.rs) and at runtime in case a certain combination of database migrations/rollbacks messes up the order.

Unfortunately not, because:
a) Informations about the requested column names are not available at runtime
b) how would you handle complex select clauses at compile time. 
(Side note: The field ordering in a auto generated `table!` call is deterministic, so that won't be a issue)

Duplicate to #2011 (and some other issues)

Could probably be resolved by introducing something like #2038
