### ISSUE TITLE
SQL SERVER support

### ISSUE THREAD

**Issue by young-altair** [diesel-rs/diesel#2201]
I know that there is now Tiberius as A pure-rust TDS implementation for Microsoft SQL Server (>=2008). 
Will Diesel support this Microsoft product or add Tiberius into one of the support drivers?
Thanks.

**Comment by weiznich** [comment]
Diesel won't add support for a closed source backend to the main crate because this would complicate the setup for potential users and contributors.

That said it is totally possible to implement support for additional database backends as third party crate. See [diesel-oci](https://github.com/GiGainfosystems/diesel-oci) for an example. If you are interested in implementing and maintaining such a crate I can provide some more details/support about how to implement it.
