### ISSUE TITLE
Custom types with same name in different schemas don't work due to oid caching

### ISSUE THREAD

**Issue by Boscop** [diesel-rs/diesel#2203]
When you have a custom type (e.g. using `diesel-derive-enum`) with the same name in different schemas, it doesn't work with diesel, it doesn't consider the search_path when looking up types.
Instead, diesel uses the first type that matches the name, regardless of the schema it's in.

It seems like this PR introduced this behavior: https://github.com/diesel-rs/diesel/pull/2088

Btw, it looks like jdbc had the same issue:
https://www.postgresql.org/message-id/flat/20110308183723.08A5B1337B93%40mail.postgresql.org

**Comment by weiznich** [comment]
Please not that this behaviour was not introduced in that PR, the query does just not check the corresponding search path.
I think it should be not that hard to fix issue. Basically we only need to add way to have a optional schema/search path for custom types. Otherwise public will be assumed as search patch. Fortunately the next release will be 2.0 so we are able to tweak the API a bit here.

Steps to implement this change:
* Change [`PgMetadataLookup::lookup_type`](https://github.com/diesel-rs/diesel/blob/8396134f1fb581529070de0b2a946f1c7d5f9e91/diesel/src/pg/metadata_lookup.rs#L25) to have a additional optional parameter for the schema name.
* Adjust [this](https://github.com/diesel-rs/diesel/blob/8396134f1fb581529070de0b2a946f1c7d5f9e91/diesel/src/pg/metadata_lookup.rs#L30-L34) query to use that optional schema name.
* Change [`PgMetadataCache`](https://github.com/diesel-rs/diesel/blob/8396134f1fb581529070de0b2a946f1c7d5f9e91/diesel/src/pg/metadata_lookup.rs#L44) to store also the schema name.
* Change the [`SqlType` derive](https://github.com/diesel-rs/diesel/blob/8396134f1fb581529070de0b2a946f1c7d5f9e91/diesel_derives/src/sql_type.rs#L90-L140) to have an optional schema parameter (basically like the type_name parameter, but optional) and pass it [here](https://github.com/diesel-rs/diesel/blob/8396134f1fb581529070de0b2a946f1c7d5f9e91/diesel_derives/src/sql_type.rs#L124) to the changed lookup function.
* Add a test case to [this file](https://github.com/diesel-rs/diesel/blob/8396134f1fb581529070de0b2a946f1c7d5f9e91/diesel_tests/tests/custom_types.rs)

**Comment by Boscop** [comment]
> - Change the SqlType derive to have an optional schema parameter (basically like the type_name parameter, but optional) and pass it here to the changed lookup function.

@weiznich But wouldn't that fix the schema at compile-time, so that that custom type only works in that one schema? 
That wouldn't solve our problem, we are using the same enum type in multiple schemas that are created at runtime based on user input (but structurally the same for all tables).
So the set of schemas that the enum type will be used in is not fixed/known at compile-time.
It needs to do the lookup based on the current `search_path` at runtime!

**Comment by weiznich** [comment]
If you have "the same" type in multiple schema they remain different types. You wouldn't consider the same rust type definitions in different modules to be resolved to the same type, right?

**Comment by Boscop** [comment]
@weiznich It's static definition vs dynamic instances. Like having 1 struct and multiple instances at runtime. We have 1 "schema" (in the sense of a set of schemas for a set of tables) and multiple instances at runtime (multiple pg schemas). 
Being able to "mount" one of these instances to a set of static types (that represent this "schema") based on the `search_path` is a valid use case IMO. 
At least it's our use case (multi-tenant system with one schema instance per tenant).
Would it be possible to accommodate this use case in Diesel or do you think it'd be too disruptive / inefficient?

**Comment by weiznich** [comment]
If you have the "same" types in different schemas that's only a interpretation added on top of the actual types. It's nothing we can infer (because matching by name/whatever will fail for constructed edge cases). That means it will be never something that will be supported by diesel out of the box in my opinion. That said it should be possible to support such an setup by implementing some things manually.
The probably easiest way to do that with the latest released diesel version is to just set the search schema dynamically by just calling `SELECT pg_catalog.set_config('search_path', 'your_schema', false);`.

**Comment by sgrif** [comment]
One thing that's important to note is that getting the current search_path requires a round trip to the database, which defeats the purpose of caching the result in the first place. I'm not sure what the right answer is here, but I think there's some missing context here. Duplicating a type per-schema seems like an anti-pattern to me. If the type is the same for all schemas, why does it need to be schema specific in the first place?

**Comment by sgrif** [comment]
@Boscop Can you clarify what you're asking for here? Is your issue that the query itself doesn't take the search path into account? Or that we cache the answer, but that may change if the search path changes?

**Comment by sgrif** [comment]
So it seems like there are three issues here:

- We don't take the search path into account on lookup
- There's no way to specify an explicit schema
- If the result *were* based on the search path, the answer could change between calls

I believe the first two can be solved by changing the where clause on our query to `WHERE oid = $1::regtype::oid`. This would also resolve schemas for us (though we should make sure this still works when given an explicit schema that isn't in the search path). We can also just narrow the schema manually if the string contains a `.`, but that'd be more complicated and also break any types with a `.` in the name (which probably won't actually break any real code)

The third problem is something I consider to be extremely niche, but it seems like we could support it by providing a second lookup function which doesn't cache the answer. But if you can't tell us the schema you want us to look in, I don't see any way we could possibly support that without doing a query every time the lookup needs to be performed.

**Comment by pietroalbini** [comment]
crates.io is hitting this problem too as we need to add our first custom type, and the fix @weiznich committed in https://github.com/diesel-rs/diesel/commit/9b8b724a3a486d98089ccd1c8ecaadb70da7eb92 is only present in the master branch (targeting 2.0). Is there any chance the fix could be backported to 1.4.x?

Also, the fix does not seem to cover all cases, as the *order* of the search path is not respected. Let's assume type `Ty` is created first on schema `foo` (type OID 5000) and then on schema `bar` (type OID 5001). [The query used to fetch the OID](https://github.com/diesel-rs/diesel/blob/e7c98fc4460dad0045386658a9f2cdc2b23d0082/diesel/src/pg/metadata_lookup.rs#L95-L107) will always return OID 5000 if both schemas are in the search path, even when `bar` is before `foo` in the search path, as no sorting is done.

I have a minimal repro in [this gist](https://gist.github.com/pietroalbini/68af598b2107b8bfb23a7ab00ecfac11), which fails on both Diesel 1.4.8 (as the search path is ignored) and Diesel master (as the *ordering* of the search path is ignored).

**Comment by pietroalbini** [comment]
To give additional context on why crates.io uses multiple schemas with overlapping types (only in our test suite), most of our tests use a single connection with `begin_test_transaction()` on the `public` schema, as that's faster than creating a new schema and running migrations on it for each of the hundreds of tests. Still, some of the tests can't use `begin_test_transaction()` for a variety of reasons [^transaction], and just for those tests we need to create a fresh schema and run migrations on it.

The search path for tests using a fresh schema has to be `$random_name, public` though, since extensions can only be initialized in a single schema for the whole database and we can't initialize them in each of the fresh schemas (we're running tests in parallel). This causes Diesel to confuse the types defined in the fresh schema (the ones dedicated to the specific test) and the types defined in the `public` schema (the ones used by all tests relying on `begin_test_transaction()`).

Right now the most promising solution for us is to simply avoid adding the custom type and work around that, but it'd be nice to see this fixed so that in the future we could actually start using custom types.

[^transaction]: One of the things we implemented a couple months ago in crates.io is the ability to serve most download requests when the underlying database fails, to reduce the impact of outages. To ensure this doesn't break we added back then multiple tests simulating database failures and checking how the database pool reacts to them (like closing all the TCP connections between the app and the database). This requires multiple connections to properly work, preventing us from using `begin_test_transaction()`.

**Comment by pietroalbini** [comment]
Glad to see it was fixed! Thanks for the really quick turnaround.

> This depends a bit on how important the fix is for the crates.io team. If it's fine to wait a few more weeks for the first 2.0 release using the master branch + migrate to that I would not do any backport to 1.4.x, especially as the code changed quite a bit since the 1.4.0 release. If you need that fix in the next few days we can talk about backporting a limited version of all that changes. In that case I would suggest to only backport this specific fix (as it changes the query only sligtly), and not the whole caching stuff.

I think we're going to use the workaround for now (an array of `int`s instead of `(int, int, int)`), so crates.io won't need a backport. If a backport were to happen I agree it'd be better to only backport the fixed query and not the caching code.

> Just to point the obvious here: Changing the search path on any existing connection will likely have "funny" side effects.

Definitely! We're only setting the search path at the start of the connection, or before executing any Diesel query anyway.

> As semi-related side note: Diesel normally distinguishes between sql side types and rust side types. Your minimal example uses the same type for both. The classical diesel style has an distinct type for the sql side, that is just a zero sized struct (and derives SqlType + QueryId).

TIL!
