### ISSUE TITLE
Diesel "Getting Started" Guide Note on Installing diesel_cli Doesn't Work as Advertised

### ISSUE THREAD

**Issue by akesling** [diesel-rs/diesel#2214]
### Versions

- **Rust:** 1.38.0
- **Diesel:** 1.4.0
- **Database:** MySQL
- **Operating System:** MacOS Catalina 10.15.1 

### Cargo Command

cargo install diesel_cli --no-default-features --features mysql

## Problem Description

The Diesel getting started guide indicates that diesel_cli should be installed.  It provided a note that suggests if one sees an error such as "**note: ld: library not found for -lmysqlclient**" that either the library should be installed/configured differently _**or**_ that the provided command should fix the issue.

The provided command (above) produces the same error.

### What are you trying to accomplish?

Install diesel for use with MySQL

### What is the expected output?

Successful installation

### What is the actual output?

https://gist.github.com/akesling/da7a849c15d0f1cb11c22c3c9c2d211e

### Are you seeing any additional errors?

Yes, see gist above.

### Steps to reproduce

Run "cargo install diesel_cli --no-default-features --features mysql" on MacOS.

## Checklist

- [ x ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ x ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
If you want to use the mysql backend you need to install the corresponding native library. This is literally stated in the sentence before that one you cited. The other option only applies to backends you don't want to use.
Additionally we use the bug tracker to track feature request and bugs not to answer questions. Please use our [gitter channel](https://gitter.im/diesel-rs/diesel) or the [forum](https://discourse.diesel.rs/) for that.

**Comment by weiznich** [comment]
> The getting started guide explicitly stated either or:
>>    You can resolve this issue by either installing the library (using the usual way to do this depending on your operating system) or by specifying the backends you want to install the CLI tool with.

> (emphasis mine)
> If the guide is incorrect, then that's the source of my confusion and it should be a fixed (thus this is still a bug, just with the guide).

I don't think the guide is incorrect, that would mean nobody other noticed that in the last 2 years which is quite unlikely.

To cite the whole paragraph:
> This means you are missing the client library needed for a database backend – mysqlclient in this case. You can resolve this issue by either installing the library (using the usual way to do this depending on your operating system) or by specifying the backends you want to install the CLI tool with.

The first sentence is quite explicitly saying that a client library is missing for some backend, which implies for me that this library is required for a specific backend.  The name of the library also clearly states that this backend is mysql. The second sentence indeed says that you could resolve that error either with installing the libs or specifying the backend you want to install. For me this does not mean that this choice is independent from what backend you want, but depending on you use case either one or the other variant is the solution you are looking for. Could be that I'm missing a nuance there as English is not my native language but for me this is pretty clear.
Anyway if you have a better wording there feel free to submit a PR changing that specific paragraph to the [correct repository](https://github.com/sgrif/diesel.rs-website/blob/master/source/views/guides/getting-started.html.slim#L85-L97).

> That being said (whether this is a bug in the documentation or the actual install), why can't this dependency be resolved wholly within Cargo / via crates? Why does there need to be an out-of-band dependency resolution?

This is not really possible because those database client libraries are plain old c libraries. Cargo does not control them therefore it cannot be managed via cargo. In theory it is possible to rewrite them in rust but at least for diesel that is out of scope. If someone does maintain such a rewrite in rust we may look into replacing the native dependency.
