### ISSUE TITLE
libintl-8.dll not found

### ISSUE THREAD

**Issue by chrislearn** [diesel-rs/diesel#2231]
### Versions

- **Rust:** 1.39.0
- **Diesel:** 1.4.0
- **Database:** postgresql 12
- **Operating System: ** Windows 10 pro for workstations. 10.0.19033 build 19033

## Problem Description
I just install diesel_cli use this command: ```cargo install diesel_cli --no-default-features --features postgres```, and it is done without error. But when I type diesel, it will give me error: 
![image](https://user-images.githubusercontent.com/5874864/69783665-f051c200-11ee-11ea-9e6b-441b2cb60154.png)

**Comment by weiznich** [comment]
You need to install that dependency. Check the documentation of `libpq` for their subdependencies.
Otherwise: This issue tracker is for tracking feature requests and bugs for the diesel team. For asking questions use our [gitter channel](https://gitter.im/diesel-rs/diesel) or our [forum](https://discourse.diesel.rs/)
