### ISSUE TITLE
Support for relaxed type checks

### ISSUE THREAD

**Issue by netvl** [diesel-rs/diesel#2256]
sqlite has very weak type checks, and you can do something like
```sql
SELECT * FROM some_table WHERE id = 'abcde'
```
even if the `id` field is `INTEGER`, and if `'abcde'` happens to be a numerical string, it will even work correctly.

Unfortunately, it is not possible to rely on this functionality with diesel, because it has strong type checks for columns. While this is a very good thing in general, it would be great if there was a way to "disable" type checking for certain use cases.

Maybe it is related, but diesel also does not seem to have support for the `CAST(expr AS type)` expression. Without either the relaxed type checks or this operator, there is no way for me to rely on the database for type conversions from strings to specific types, which I would very much like to do - specifically, I have a `String` input value which might actually be an integer, and I want to use this value to filter against several columns in the database, both integers and strings. It seems that with the existing API, I will necessarily have to try and convert the input string to an integer inside my program.

**Comment by netvl** [comment]
Ok, I guess "no way" is a bit strong, I can certainly use `sql()` to write raw SQL, but naturally this is not the best possible solution :)

**Comment by weiznich** [comment]
I do not see that as something that should be supported in diesel itself, because that undermines all our type safety stuff. 
That said, I see that there could be valid use cases to do something like that (legacy data…). Fortunately it is possible to implement the required functionality outside of diesel. What you want is something like [this](https://github.com/diesel-rs/diesel/blob/6404b7ebc2e9e59840bdd122020611b7903f94ce/diesel/src/expression/coerce.rs). Please note that this is only some diesel internal thing, so this type is not exposed as part of the public API. It should be easily possible to just copy the definition and all trait implementations there and have such a type as part of your crate. All required trait implementations there are possible with the public API.

I close this issue because I do not see anything actionable for the diesel team here.

**Comment by netvl** [comment]
@weiznich thanks, that coerce thing seems useful.
