### ISSUE TITLE
Can queries be copied, duplicated in any way?

### ISSUE THREAD

**Issue by sbidin** [diesel-rs/diesel#2277]
I'm building two queries (one to count some data, another to fetch a subset of the data). They're both very similar. The only difference is that one uses `offset` & `limit`, while another one uses `count`.

Ideally, I'd prefer not to have to define them twice in full, since I'd be mostly duplicating code.

Is there any way to create the base (common) query only once? Something like...

```rust
let common = table.filter(table::column.eq(...)).into_boxed();
let a = common.wishlist_duplicate().offset(50).limit(10);
let b = common.wishlist_duplicate().count();
```

If not possible, I can always fall back to defining the two queries separately, so it's not a showstopper.

Love diesel :heart: & thanks in advance for any help you can provide!

Edit: I've found #1698 that seems relevant, but I'm not 100% sure I need an implementation of `Clone`.

**Comment by weiznich** [comment]
If you use a boxed query there this is not possible because of the reason outlined in #1698 (`Clone` is not object safe.)

Without the `.into_boxed()` call this should work just fine for this specific query, because that one should be `Copy`. 
In general that's not so easy to answer, because there are some query fragments that are just not copy. An example is everything that uses `eq_any` to bind some list of values.

I'm closing this issue, because I do not see anything actionable for the diesel team here. Feel free to ask further questions in our gitter channel or forum.
