### ISSUE TITLE
Feature: Provide a method to create a DB::RawValue for tests

### ISSUE THREAD

**Issue by Diggsey** [diesel-rs/diesel#2285]
This could be as simple as making the existing methods on the various RawValue types public:
`pub fn for_test(raw_value: &'a [u8]) -> Self`

I think it should be fine to leave it as `cfg(test)`?

**Comment by weiznich** [comment]
At least for [sqlite](https://github.com/diesel-rs/diesel/blob/master/diesel/src/sqlite/connection/sqlite_value.rs#L13) this is not possible, because the `RawValue` type there does not contain any bytes, but a ffi type.

Additionally I'm not happy with exposing the internals of those types anywhere in some sort of public API, because we've specially have those types to hide those internals. This allows use to add features like those dynamic query abilities coming in diesel 2.0, without having a breaking change there. If we now expose the internals, we can never change them again.

**Comment by Diggsey** [comment]
`PgValue` already has a `pub fn as_bytes(&self) -> &[u8]` - there's no way to implement this that doesn't involve it owning or borrowing a byte slice, so I don't think that adding this method would impose any additional restrictions.

For `sqlite` the only public methods are the `read_xx` and `is_null` methods - it would still be useful to be able to mock a value which gave a particular result from these methods. For example, `cfg(test)` could turn these values into an enum of `Real(...) | Mock(...)`.

**Comment by weiznich** [comment]
> PgValue already has a pub fn as_bytes(&self) -> &[u8] - there's no way to implement this that doesn't involve it owning or borrowing a byte slice, so I don't think that adding this method would impose any additional restrictions.

That only says that `PgValue` is required to contain at least a byte slice, but not what else is part of `PgValue`. For example if we add some information about the type on database side we would require that information somehow to construct the value, which would imply changing the `for_test` function, which would be a breaking change.

> For sqlite the only public methods are the read_xx and is_null methods - it would still be useful to be able to mock a value which gave a particular result from these methods. For example, cfg(test) could turn these values into an enum of Real(...) | Mock(...).

a) `SqliteValue` is not even part of the public API. Again, that's by design. That may change in the future, but at least all those methods you mentioned there will not be part of public API in a foreseeable future. 
b) Its not clear for me how a mocked version of the the ffi type that would look like without having a nested mess of enums. Also reproducing the functionality provided by the sqlite interface will not be straight forward, because you would require quite dynamic implementation specific casting rules there.

In general the best way to test custom `FromSql`/`ToSql` implementations is to just do a database round trip. (Probably in combination with something like quickcheck or fuzzing). That cannot be replaced by mocking, because otherwise the mocking layer would be required to reproduce all functionality of the database there, which would be out of scope for diesel.

**Comment by sgrif** [comment]
Just to add some additional weight behind @weiznich's point (which I agree with), we don't directly test `FromSql` even in Diesel, only the behavior of `SELECT literal`. Arguably we should have some more direct tests, but that seems purely redundant to me since you still need the tests we have to day to demonstrate our assumptions about what the DB actually sends us is correct. (We do have some direct tests for `FromSql`, and this argument probably applies to those as well. Especially since in general, `assert_eq!(serialized_value, some_array_of_bytes)` is extremely hard for a human to look at and determine whether the test is even correct or not)

As @weiznich pointed out, this would limit what we changes we could actually make to these structures in the future, and the whole point of removing the cases where we had `&[u8]` directly was to enable us to freely add more fields going forward. If you're just trying to write unit tests for some logic that only needs a byte slice, it's really easy to move the logic to its own function, and test that directly.

**Comment by Diggsey** [comment]
Fair enough.
