### ISSUE TITLE
Add top-level `literal` function to simplify passing literal values

### ISSUE THREAD

**Issue by Diggsey** [diesel-rs/diesel#2286]
It's quite hard to generate SQL like `SELECT "literal string"` from diesel unless you really know what you're doing:

```rust
diesel::select(AsExpression::<Text>::as_expression("literal string"))
```

It would be more discoverable (and not rely on UFCS) to have a `literal` function:
```rust
diesel::select(diesel::literal::<Text>("literal string"))
```

**Comment by weiznich** [comment]
There is already a shortcut for this: [`IntoSql`](http://docs.diesel.rs/diesel/expression/trait.IntoSql.html), 

so that you would just write `"literal string".into_sql::<Text>()`

**Comment by Diggsey** [comment]
Ah thanks. Still, even though I've used diesel quite a bit, it's easy to forget these things and they are difficult to [re-]discover.

Just an idea: have you thought about collecting a set of example SQL queries and their equivalents in Rust. For people who are already well acquainted with SQL it would make finding these things much easier.

eg.

| SQL | Diesel |
| --- | ------- |
| `SELECT "literal"` | `diesel::select("literal".as_sql::<Text>)` |
| ... | ... |

**Comment by weiznich** [comment]
It may be useful to have some example queries at the top of the API docs. The problem is: Currently nobody of the contributors team has time to write them. It's more important for us fix issues that are blocking for projects where we use diesel on our own. That means we would happily accept such a contribution, but we will probably not have the time to work on this on our own (At least I wont have that time in the foreseeable future).
