### ISSUE TITLE
Running "diesel database reset" causes all tests to recompile

### ISSUE THREAD

**Issue by cars10** [diesel-rs/diesel#2311]
### Versions

- **Rust:** 1.41
- **Diesel:** 1.4.3
- **Database:** mysql
- **Operating System**: Manjaro

### Feature Flags

- **diesel:** ["mysql", "chrono"]

## Problem Description
Everytime i run `diesel database reset` my integration tests recompile when i run `cargo test`.

### What are you trying to accomplish?
Always reset the database before running my tests.

### What is the expected output?
Tests should not need to recompile. I would expect that `diesel database reset` only executes my sql migration files and does not touch any sourcecode. Even if it does, the sourcecode should be the same as before.

### What is the actual output?
I have to recompile the tests.

### Are you seeing any additional errors?
Nope

### Steps to reproduce
This is the script i currently use:

```bash
diesel database reset
RUST_TEST_THREADS=1 cargo test
```

When i run it then cargo always recompiles my integration tests. If i remove `diesel database reset` then the tests are simply executed without recompilation each time (if i did not do any over code changes obviously). Manually executing all my migration sql files obviously also does not result in having to recompile my tests.

**Comment by weiznich** [comment]
I would call this expected behaviour. `diesel database reset` does delete and recreate the database, while recreating the database migrations are applied and a new version of `schema.rs` is generated, so the timestamp of that file changed. This is then picked up by cargo and will cause the recompilation of your tests. (The same is true for actually reapplying only the transactions.) As it's quite hard to tell if not a migration or something changed while doing the database reset I do not see an meaningful way to change this behaviour.
A probably better solution for your initial problem is to use `Connection::begin_test_transaction` to prevent writing data to the database.

I'm closing this issue as not actionable. If you disagree with this, feel free to add some arguments and implementation ideas as comment.

**Comment by cars10** [comment]
Thanks for the explanation. I cannot use `begin_test_transaction` because my code uses many transactions already. Running a transaction within `begin_test_transaction` causes it to commit anyway so this does not help.

Is there a way to stop diesel from recreating the `schema.rs` every time i run `diesel database reset`?

**Comment by weiznich** [comment]
See the [corresponding guide](http://diesel.rs/guides/configuring-diesel-cli/) for informations how to configure diesel-cli. Basically you need to have a `diesel.toml` file without `[file]` entry to disable auto generating a `schema.rs` file.

**Comment by cars10** [comment]
Thanks!
