### ISSUE TITLE
Report clearer error message when column limit is reached

### ISSUE THREAD

**Issue by bobobo1618** [diesel-rs/diesel#2312]
### Versions

- **Rust:** rustc 1.41.0 (5e1a79984 2020-01-27)
- **Diesel:** 1.4
- **Database:** PostgreSQL
- **Operating System** Arch Linux

### Feature Flags

- **diesel:** `"postgres", "chrono", "64-column-tables"`

## Problem Description

When creating a schema for a table with a number of columns exceeding the limit, arcane error messages like the ones encountered by [this user](https://stackoverflow.com/questions/55783064/the-trait-dieselexpression-is-not-implemented-for-bigdecimalbigdecimal) appear:

`the trait \`diesel::SelectableExpression<schema::posts::table>\` is not implemented for (insert list of columns here)`

Coming from other ORMs, it's unexpected that a column limit is even something that's possible. It is documented in a couple of places but I think that it's unlikely I'd look in those places when seeing an error message like the one above.

### What are you trying to accomplish?

Regular development using Diesel.

### What is the expected output?

An actionable error message telling me what I need to do to fix the issue.

### What is the actual output?

An arcane error message that misdirects me in another direction.

### Are you seeing any additional errors?

No.

### Steps to reproduce

Attempt to compile a table with more than 32 columns without a higher limit switched on.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
> When creating a schema for a table with a number of columns exceeding the limit, arcane error messages like the ones encountered by this user appear:

The stackoverflow post you linked contains an error that has nothing to do with the content of this issue.

> Coming from other ORMs, it's unexpected that a column limit is even something that's possible. It is documented in a couple of places but I think that it's unlikely I'd look in those places when seeing an error message like the one above.

Having this restriction is a result of providing various compile time checks like does the column you select exists on a table in your from clause. Internally this does require us to implement traits for tuples of different sizes. Because of restrictions in the language we cannot write on trait implementation for tuples of all sizes, but need to write a implementation per tuple size, so one for 1 element tuple, one for two element tuples and so on. That implies we need to stop somewhere doing this. As having all this impls will greatly increase the compile time of diesel, we decided to default to a max size of 32, while having feature flags up to 128 elements. Beyond that compile times are just so bad that you don't want to use it. (Additionally having more than 128 columns in a table is clearly bad design).

About the error message: As this error message is related to rusts type system and triggered by rustc we do not have any control about it. 


Closed because there is really nothing we can do about this error message.

**Comment by bobobo1618** [comment]
I understand that you can't alter the output of Rust's type system but is it not possible to use static assertions (like those provided by [this crate](https://crates.io/crates/static_assertions)) to provide an extra, clearer error message?

**Comment by weiznich** [comment]
And at which point we could do this static assert? That would need to be part of diesel itself, but there we don't know how many columns you will provide.
