### ISSUE TITLE
Missing example for QueryableByName

### ISSUE THREAD

**Issue by Mingun** [diesel-rs/diesel#2350]
Getting started guide has very limited examples of how to make selects, in particular, `QueryableByName` usage not covered at all.

### Versions

- **Rust:** rustc 1.42.0 (b8cedc004 2020-03-09)
- **Diesel:** 1.4.4
- **Database:** sqlite
- **Operating System:** Windows 10

### Feature Flags

- **diesel:** sqlite

### What are you trying to accomplish?
Query some part into struct, that implements `QueryableByName`. Ideally I shouldn't specify nothing else except the `Data` type itself, because diesel already known from which table (because I specify `table_name`) and which columns (== names of struct fields) it must select.

### What is the expected output?
Successfull compilation

### What is the actual output?
With and without commented line I get the error, only count of additional elements in tuple changed:
```bash
error[E0277]: the trait bound `Data: diesel::Queryable<(..., diesel::sql_types::Integer, diesel::sql_types::Text, ...), diesel::sqlite::Sqlite>` is not satisfied
  --> src\main.rs:27:8
   |
27 |       .load(&connection)
   |        ^^^^ the trait `diesel::Queryable<(..., diesel::sql_types::Integer, diesel::sql_types::Text, ...), diesel::sqlite::Sqlite>` is not implemented for `Data`
   |
...
```
So how I must write the code to get it work?

### Are you seeing any additional errors?
No

### Steps to reproduce

```rust
use diesel::prelude::*;
use diesel::sqlite::SqliteConnection;

table! {
    data (_id) {
        // ...something other...
        modified_date -> Integer,
        content -> Text,
        // ...something other...
    }
}
#[derive(Debug, QueryableByName)]
#[table_name = "data"]
pub struct Data {
  pub modified_date: u32,
  pub content: String,
}
fn main() {
  use data::dsl::*;

  let connection = SqliteConnection::establish("file:test.db").unwrap();
  let results: Vec<Data> = data
      //.select((modified_date, content))
      .load(&connection)
      .expect("Error loading data");
}
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
The guide is not expected to cover all cases. Especially the getting started guide is a guide to well getting started on developing something with diesel, not to provide a full understanding of the whole crate. (This is something that is impossible to cover in one or even multiple guides.)
Generally our API documentation is the right place to search for more informations. [There are examples](http://docs.diesel.rs/diesel/deserialize/trait.QueryableByName.html) for `QueryableByName` and the documentation there does also state that it can only be used in combination with `sql_query`.

Another general note: Please do not try to transfer knowledge about how other ORM's do something like a model object to diesel. Diesel does not work this way, there is no such thing like a central model entity provided by diesel itself.

**Comment by Mingun** [comment]
> The guide is not expected to cover all cases.

And where is expected? This information is not available anywhere on the official website. Where else to look for information like not in the official manual? Please, consider this issue as request to improve guide to cover at least base usage of all features.

> [There are examples](http://docs.diesel.rs/diesel/deserialize/trait.QueryableByName.html) for `QueryableByName` and the documentation there does also state that it can only be used in combination with `sql_query`.

I will allow myself to disagree. That examples not shown how I can solve my example. The usage of `sql_query` in the docs does not look like it is the only possible use, but only as one of them, that used here just to simplify example. And if so, consider this issue as feature request. I see no reasonable reasons not to work in a described way.

> Please do not try to transfer knowledge about how other ORM's do something like a model object to diesel

I didn't work with any other ORM. Here I made quite logical remarks, visible to the naked eye. And if the ideology of diesel is different from that generally accepted in other ORMs, then more examples are especially needed. If you think you don't have time to make them yourself, at least you can let others do it for you. Of course, it is impossible to make examples on all cases of life, but it should be sought.

**Comment by weiznich** [comment]
> And where is expected? This information is not available anywhere on the official website. Where else to look for information like not in the official manual? 

The name of the guide implies that: "Getting Started" not something like "Everything about diesel".
The canonical source of information about diesel are the API docs, guides are available for selected topics, not for everything. That's not possible. And no I do not see any reason to explicitly mention that anywhere, as it is the same for basically all of the rust ecosystem.

For questions about constructing select statements is generally a good idea to look at the documentation of [`QueryDsl`](http://docs.diesel.rs/diesel/query_dsl/trait.QueryDsl.html). Generally searching the API documentation just by the corresponding SQL you are looking for does yield the right results. That's also stated as one of the [first things](http://docs.diesel.rs/diesel/index.html#where-to-find-things) in the API documentation.

> I will allow myself to disagree. That examples not shown how I can solve my example. The usage of sql_query in the docs does not look like it is the only possible use, but only as one of them, that used here just to simplify example. And if so, consider this issue as feature request. I see no reasonable reasons not to work in a described way.

It's literally the first thing stated by the docs of `QueryableByName` that it supports only queries constructed by `sql_query`:

> Deserializes the result of a query constructed with sql_query.

As for the feature request, please see the duplicate #2037 for reasoning why this is not really possible. (Basically the same applies to `QueryableByName` in this context to + even if we had those information we cannot integrate it with the current `RunQueryDsl` API because of conflicting trait implementations (that's a language limitation))

> I didn't work with any other ORM. Here I made quite logical remarks, visible to the naked eye. And if the ideology of diesel is different from that generally accepted in other ORMs, then more examples are especially needed. If you think you don't have time to make them yourself, at least you can let others do it for you. Of course, it is impossible to make examples on all cases of life, but it should be sought.

First of all I do consider calling the maintainers of some open source project as blind or illogical as not constructive and really rude. Don't do that again here. Beside of that please remember for future request that we do develop and maintain diesel as volunteers in our free time, so making any requests that are basically  "Why does this not work?" without any research in previous discussions is basically a waste of free time of other people. Please consider that for future comments.

Beside of that yes we should probably improve documentation at some location, but again I do only have a certain amount of time a can spend on working on diesel. In that time I generally prioritize the following things in this order:
* Features I need for my own research work at university
* Features other people paying me implement
* Features required by Sean/crates.io/other core team members
* Mentoring people working on specific issues/features/documentation
* Anything else, like writing new documentation for existing features by myself.

Given my current time constraints I'm consider me generally happy if I find at least some time for mentoring. Answering such issues generally takes that bit of time away. (And yes I know documentation is generally important)

So sure if you want to improve documentation go and and provide a PR. Otherwise please try to write at least a issue that makes exactly clear what should be clarified where. That's not the case for this issue, because you talk about the getting started guide that does not even mention `QueryableByName`. The only context where this trait is mentioned is in the context of `sql_query`.

**Comment by Mingun** [comment]
> The canonical source of information about diesel are the API docs, guides are available for selected topics, not for everything.

API docs answers for "How?" question, now for "Why?" question. "Why?" question should be covered by guides, and now diesel have no such guide for most used operation -- `select`. Anyway, why you have topics "[All About Inserts](http://diesel.rs/guides/all-about-inserts/)" and "[All About Updates](http://diesel.rs/guides/all-about-updates/)", but not "All About Selects"? In typical application reading data much more often task than inserting or updating.

> For questions about constructing select statements is generally a good idea to look at the documentation of [`QueryDsl`](http://docs.diesel.rs/diesel/query_dsl/trait.QueryDsl.html). 

And how does the user have to guess what to look at there? `QueryDsl` is not mentioned in any of the guides on the https://diesel.rs. When the user writes the code, when will (s)he receive the object implementing this trait to even at least guess that (s)he should look at it? And even the documentation for this trait doesn't explain how to use it at all, because it answers to question "How?" but at that moment user need firstly to answer to questions "What?" and "Why?". API documentation, however detailed, is useless if you cannot tell the user when they should use the API. Great documentation by this and different from good.

As example of very excellent documentation I can suggest to look at https://gojs.net/latest/learn/index.html.

> It's literally the first thing stated by the docs of `QueryableByName` that it supports only queries constructed by `sql_query`:

Unfortunately, it is still impossible to read as "used only for result of `sql_query`". For a thing of this type, it's more logical to expect a name `SqlQueryResult`. But `QueryableByName`
* collocates with the `Queryable` trait, that used for any selects, so logically it seems that it is the same as `Queryable`, but with additional meta-information
* requires `#[table_name = ...]` or `#[sql_type = ...]` on each field
** which logically leads us to the fact that if we specify a table, we will provide all the necessary information to retrieve the necessary data. For example, that can be implemented, as implementing additional trait `Table`:
```rust
pub trait SubsetOfTable: QueryableByName {
  pub type SqlType: ...;
}
// generated
mod foo {
  struct table;
  impl SubsetOfTable for table {
    type SqlType = (columns::field1, columns::field2, ...);
  }
  mod columns {
    struct field1;
    struct field2;
    ...
  }
}
// use <table as SubsetOfTable>::SqlType instead of select((columns::field1, columns::field2, ...)) written manually in load() or whatever
```

> First of all I do consider calling the maintainers of some open source project as blind or illogical as not constructive and really rude.

I'm not saying you're blind or anything. However, it is foolish to deny the fact that when you work with something for a long time, you can subconsciously not notice the problems of other people, simply because you have already learned to bypass them at the subconscious level.

> Beside of that yes we should probably improve documentation at some location, but again I do only have a certain amount of time a can spend on working on diesel. In that time I generally prioritize the following things in this order:

As I said, I don't suggest that you do all the work, but washing away from users' questions by just closing their issues and saying that everything is already there, look in the API -- it's a signal to me that maintainers don't want to accept other people's help. Just to say, "yes, we have problems in the documentation, we would be happy if you do PR _here (link to the file in the repository, where improvements can be made_)" will be enough. I have been watching projects for a long time and unfortunately see this unpleasant trend.

> So sure if you want to improve documentation go and and provide a PR.

I could try to write "Something About Selects", which will cover the use of `Queryable` and `QueryableByName` and maybe some related things to read data from an _existing_ database (although I'm not sure this job is at all under the power of a rookie in diesel), but I need an indication in at least which repository to do so. Besides, I'm not a native speaker, so my language may be wrong.

**Comment by weiznich** [comment]
> Anyway, why you have topics "All About Inserts" and "All About Updates", but not "All About Selects"? In typical application reading data much more often task than inserting or updating.

Quite simple: Nobody was willing yet to invest time to write such an guide, as covering everything relevant about selects is a lot of work, probably much more than all existing guides together.

> And how does the user have to guess what to look at there? 

It's mentioned in the beginning of the API docs in the "where to find things section" :wink: And yes I expect users to look at the API docs, even if there are existing guides.

>  Great documentation by this and different from good.
> As example of very excellent documentation I can suggest to look at https://gojs.net/latest/learn/index.html.

I know how great documentation looks like, but that does not necessarily mean that I prioritize writing them myself. End the end it's important for me to get my work done. It may sound hard, but I can do that without great documentation but not without specific features I need. So I prioritize that. That does not mean that I will stop anyone from stepping up writing better documentation or work on whatever they want.

> Unfortunately, it is still impossible to read as "used only for result of sql_query". For a thing of this type, it's more logical to expect a name SqlQueryResult. But QueryableByName

Feel free to try out your suggestion. I've been there and I can tell you it's just not possible with the current API (which we won't change, because of stability guarantees) and the current stable language features. General if you disagree with some design decision taken by diesel that's fine, but that does not mean we will change it. We have for most things quite good reasons why things are as they are. It's all documented somewhere (git commits, PR comments, …), but as this is mostly implementation dependent and highly technical I do not see any reason to mention anything of that in a user documentation.

> I'm not saying you're blind or anything. However, it is foolish to deny the fact that when you work with something for a long time, you can subconsciously not notice the problems of other people, simply because you have already learned to bypass them at the subconscious level. 

But you continue to assume we haven't thought about this yet, which is not the case. If you would do at least a bit of research in existing issue/pr's you would see that. And doing some minimal amount of research is something I expect from people opening issues here.

> As I said, I don't suggest that you do all the work, but washing away from users' questions by just closing their issues and saying that everything is already there, look in the API -- it's a signal to me that maintainers don't want to accept other people's help. Just to say, "yes, we have problems in the documentation, we would be happy if you do PR here (link to the file in the repository, where improvements can be made)" will be enough. I have been watching projects for a long time and unfortunately see this unpleasant trend.

We have stated at multiple occasions that our bug tracker is for tracking bugs (for anyone) and features requests (as long as they are put there with some communication with the diesel team). Anything else will be closed as it is not immediately actionable for someone with the reasoning to keep our bug tracker somewhat manageable. For everything else you are encourage to use the gitter channel or our forum. Again in the style you have written this issue I do not consider this as something that is actually actionable, because:
* It does mention `QueryableByName` and complains that the getting started guide does not mention how to use it. In fact the getting started guide does not even mention that trait, so linking to the "only" place (==API docs) where information about this are available is for me the right response here.
* It requested information/documentation about a feature that does not exist in this way. Again that's not actionable for someone.


> I could try to write "Something About Selects", which will cover the use of Queryable and QueryableByName and maybe some related things to read data from an existing database (although I'm not sure this job is at all under the power of a rookie in diesel), but I need an indication in at least which repository to do so. Besides, I'm not a native speaker, so my language may be wrong.

I think someone that is currently learning diesel is probably much better suited to write at last a draft of such an guide as one of the maintainers, because as you already notice: We know how this things work. As for the language: I'm not a native speaker either. Beside of that it's not like nobody will proof read what is submitted as new guide :wink:
As for the location: Draft for new guides go [here](https://github.com/diesel-rs/diesel/tree/master/guide_drafts). As soon as we are satisfied with the content of a guide we will add it to the official guide section on the web page.
