### ISSUE TITLE
Can't update from a boxed query

### ISSUE THREAD

**Issue by adamchalmers** [diesel-rs/diesel#2369]
## Setup

I've made a minimal example in a new project [here](https://github.com/adamchalmers/dieselproblems/blob/master/src/main.rs).

### Versions

- **Rust:** 1.42
- **Diesel:** 1.4
- **Database:** PostgreSQL
- **Operating System** MacOS

### Feature Flags

- **diesel:** postgres, r2d2

## Problem Description

I can't figure out how to apply several dynamic filters to a query, and then update using those filters. 

### What are you trying to accomplish?

I want a function `get_tunnels` which selects all rows from a table after applying some filters. Which exact filters get applied is only known at runtime.

### Are you seeing any additional errors?

```
the trait `diesel::Identifiable` is not implemented for `diesel::query_builder::BoxedSelectStatement<'_, (diesel::sql_types::BigInt, diesel::sql_types::Text, diesel::sql_types::Bool), tunnels::table, diesel::pg::Pg>`
```

This makes sense to me, because All About Updates says you can only pass a query into a `diesel::update` if it's only had `.filter` called on it. My query meets this criteria, but because it has to be boxed, the compiler doesn't know that.

### Steps to reproduce

Run `cargo check` in the linked repo

## Checklist

- [X ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
As you already pointed out:

> This makes sense to me, because All About Updates says you can only pass a query into a diesel::update if it's only had .filter called on it. My query meets this criteria, but because it has to be boxed, the compiler doesn't know that.

We cannot guarantee for `BoxedSelectStatment` that this is true for all cases, as we have no way to access the single clauses at compile time. Therefore using a `BoxedSelectStatement` is not supported as where clause for update statements. 

Instead of using a `BoxedSelectStatement` there, you can just [box the update statement](http://docs.diesel.rs/diesel/query_builder/struct.UpdateStatement.html#method.into_boxed) itself and apply the filter dynamically afterwards or use [`BoxableExpression`](http://docs.diesel.rs/diesel/expression/trait.BoxableExpression.html) to construct a not statically typed expression, which could be used as filter in a "static" select statement.

Closed as everything seems to work as expected.
