### ISSUE TITLE
Feature request: optional LIMIT

### ISSUE THREAD

**Issue by totorigolo** [diesel-rs/diesel#2383]
This is about a feature that I wished to be present in Diesel.

## What do you want to do, and how do you expect Diesel to support you with that?
In my HTTP API or CLI, I sometimes have an optional limit, and I wished I could just write:
```rust
let optional_limit = Some(10);
let results = posts.filter(published.eq(true))
    .limit(optional_limit)
    .load::<Post>(&connection)
    .expect("Error loading posts");
```
As of today, we have to use `.into_boxed` and `if` statements, which is quite cumbersome.

## How might this be added to Diesel?
A new function akin to `.limit`, maybe called `.maybe_limit`?

## What are possible alternatives?
`.into_boxed` and `if` statements.

## Are there any disadvantages?
I don't really know.

**Comment by weiznich** [comment]
First of all: If diesel chooses to provide such a feature it will only `BoxedSelectStatement`, because normal queries have a statically typed ast, which means you cannot add a clause conditionally. 

As such an extension is not provided for any other clause it would be a quite odd addition to diesels API. So either we need to provide a similar API for all clauses or for none.

Additionally such a functionality could easily be provided by a third party extension trait in the following way:

```
trait MaybeLimit {
    fn maybe_limit(self, limit: Option<i64>) -> Self;
}

impl<'a, ST, QS, DB> MaybeLimit for BoxedSelectStatement<'a, ST, QS, DB> {
    fn maybe_limit(self, limit: Option<i64>) -> Self {
        if let Some(limit) = limit {
             self.limit(limit)
        } else {
            self
        }
    }
}
```

From that point of view I favor not to add such an extension yet.

**Comment by weiznich** [comment]
I do not feel that this would fit nicely into the current type system for static queries. Otherwise a similar pattern is already possible for dynamic queries, therefore I close this issue.
