### ISSUE TITLE
Error when migrate using pg_dump-generated .sql file  

### ISSUE THREAD

**Issue by frbimo** [diesel-rs/diesel#2419]
### Versions

- **Rust:** 1.43.1
- **Diesel:** 1.4.4
- **Database:** postgresql
- **Operating System** ubuntu 18.04

## Problem Description
This is my first time using diesel. I used embed_migrations! on my rust code in /bin to migrate .sql file generated from pg_dump. I copied the content and put into migrations/<ts>_data/up.sql and then run it. Process returned error because of COPY () FROM stdin;

I've searched on diesel documentation related to this, but what i found was example case where .sql file was generated by diesel itself (or maybe i missed some info).

### What are you trying to accomplish?
Migrate .sql to new database. (expected to similar with pg_restore).

### What is the expected output?
migration succeed without error

### What is the actual output?
`QueryError(DatabaseError(__Unknown, "syntax error at or near \"1\""))`

### Steps to reproduce
up.sql

```
--
-- PostgreSQL database dump
--
-- Dumped from database version 10.1
-- Dumped by pg_dump version 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)

SET statement_timeout = 0;

SET lock_timeout = 0;

SET idle_in_transaction_session_timeout = 0;

SET client_encoding = 'UTF8';

SET standard_conforming_strings = ON;

SELECT
    pg_catalog.set_config('search_path', '', FALSE);

SET check_function_bodies = FALSE;

SET xmloption = content;

SET client_min_messages = warning;

SET row_security = OFF;

--
-- Data for Name: credentials; Type: TABLE DATA; Schema: public; Owner: usertest1
--

COPY public.credentials (database_pid, pseudo_id, shared_use, internal_hosts, external_hosts, username, PASSWORD, DATABASE, replica_set, deployment_method, datacenter_code, status)
FROM
    stdin;

1 1 f test test USER pass dbauth test test dc test 
-- PostgreSQL database dump complete
--

```

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
First of all a `up.sql` file is never generated by diesel itself (only an empty file is created by `diesel migration generate`). It is expected that the user writes/provides those files.

For your error message: `COPY … FROM stdin;` is designed to be executed via the `psql` command line tool. Diesel cannot support such constructs easily because libpq (the official postgres client library we use below) does not allow mixing such constructs with ordinary sql. 

`COPY … FROM stdin;` expressions are normally used to insert large amounts of data into a database, while migrations are normally used to instance the schema itself (and not to insert actual data). So I see a few possible workarounds here:
* Check if you really want to import the actual data, or only recreate the schema. If so use a dump generated with `--schema-only`
* If you really want to import the data use a dump generated with `--inserts`

(See the [postgres documentation](https://www.postgresql.org/docs/current/app-pgdump.html) for details)


I'm closing this issue as I'm considering this question answered.
