### ISSUE TITLE
Diesel insists on using older `uuid` crate

### ISSUE THREAD

**Issue by tbarusseau** [diesel-rs/diesel#2437]
### Versions

- **Rust:** rustc 1.46.0-nightly (feb3536eb 2020-06-09)
- **Diesel:** 1.4.5
- **Database:** postgres
- **Operating System:** debian

### Feature Flags

- **diesel:** `features = ["chrono", "postgres", "uuid"]`

## Problem Description

I'm using [uuid](https://crates.io/crates/uuid) as a direct dependency of my project, with version `0.7.4` (the version used to implement various traits in the `rocket_contrib` crate).

However, as seen in my `Cargo.lock` file, diesel uses the following version: `0.6.5`.

I can see in the `Cargo.toml` file of diesel that `uuid` version number is accepted like so: `version = ">=0.7.0, <0.9.0"`, so why can't cargo see that and use the already existing `0.7.4` `uuid` dependency for diesel as well?

### Steps to reproduce

- Create a new Rust project
- Add the following to `Cargo.toml`:
```
diesel = { version = "1.4.5", features = ["chrono", "postgres", "uuid"] }
uuid = "0.7.4"
```
- `cargo build`
- This minimal Rust project now features two version of `uuid` : `0.7.4` (wanted), and `0.6.5` (unwanted)

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be closed if this is not the case)

**Comment by weiznich** [comment]
I think you've looked at the `Cargo.toml` file from the master branch, where we changed the supported dependency versions. Have a look at the corresponding [file](https://github.com/diesel-rs/diesel/blob/bec389a1ea329c161fc7a8fb8df8bea29a3432bf/diesel/Cargo.toml#L26-L27) for the last release. Using the `uuidv07` feature enables support for uuid >0.6.
Unfortunately we cannot support all behind one feature flag on 1.4.x due to breaking changes in uuid itself.

Closed as this is not an actionable issue on either 1.4.5 nor on the master branch

**Comment by tbarusseau** [comment]
Ah! My mistake was assuming that master was the release branch, indeed... That explains everything (also the fact that I couldn't find the `uuidv07` feature that I saw mentioned in some other discussions).

Thanks a lot for the answer.
