### ISSUE TITLE
Long compile times on many queries

### ISSUE THREAD

**Issue by ralpha** [diesel-rs/diesel#2453]
I have notices that as my project grows and more queries are added the compile time grows a lot (but only the query part takes much much longer).

### Versions

- **Rust:** rustc 1.46.0-nightly
- **Diesel:** 1.4

### Feature Flags

- **diesel:** ["postgres", "r2d2"]

## Problem Description

This is not really a problem, but did not find any other issues that mentioned/addresses this.
As I add more and more queries to my project (some are generated by derive or macro_rules I created) my project takes longer and longer to compile.
I just did a test and commented out some of the macro's that generate more queries. And the project compile time when from 13min to 6min. (debug build, release build is effect the same way, just longer, as expected) (this is not a prefect test but gives an idea)
It is not that the macro's are very special, they just create a bunch of different queries depending on the objects.
But It is a very noticeably change. When my application is compiling it spends a very big part of its time on the DB part. Although there are many other parts that are even bigger (in lines of code and code complexity).
Note: Tests show that it is really in the Diesel code for the query creation where it spends its time. This is not my other code.

I'm talking about ~5000 queries that are being generated. Most of them to request different data from the database in different formats and forms depending on user input. I'm fully aware that this is a lot, but then again it is creating a query and it should be able to handle something like this without many problems.

I don't expect something to be done with this issue. But I just want to bring it up to give the project a heads up.

(All this is in compile time, debug and release are effected similarly, even rust-analyzer takes long to look for issues in the code. The actual runtime is not effect and runs perfect. It is just that this makes development harder and slower.)

This issue can be closed, but just wanted to mention it so it is out there, as other people might find them in a similar situation.
I don't think that much can be done about this, but yeah, at least you know.

**Comment by weiznich** [comment]
First of all this is not completely unexpected for me. Diesel does a lot of checking by using the type system. That implies that the compiler needs to verify quite a lot of trait bounds for each query. So in the end we are stressing rustc's/rust-analysers trait system component here, it may be worth to report that as performance bug there as well, but I would assume that they require a "minimal reproducible example" (i.e something that not depends on diesel). At least I do currently not have the time to minimize such an application.

As for actually actionable items for improving the compile times of a application crate using diesel:
* Depending on your table sizes, it may be worth to disable diesels default features, so that diesel only has support for tables up to 16 columns. As this removes all trait impls for tuples between 16-32 elements this should help to speedup the compilation a bit.
* The ordinary approach of speeding up the compilation of a single crate by splitting it into multiple subcrates could apply here as well.
* Generating code by macros means that the code is copied for each location, where the macro is invoked. This means rustc needs to check the constraints there again and again, so transforming the macros into generic functions could help as well
* Liberally using `.into_boxed()` (or `Box<dyn BoxableExpression>`) on queries (especially those duplicated by macros) could help as well as this removes a lot of type information in the first place. If those information are not there, rustc cannot spend time on checking them. (This comes with a small performance impact as this involves boxing + dynamic dispatch)

**Comment by ralpha** [comment]
Thanks for the info. 
I already had some of the performance improvements in place and will further try to optimize it so I can get the compile time down by a few min. Thanks for the tips above I'll definitely take a look and see what I can change!

**Comment by weiznich** [comment]
I'm closing this issue now, as I don't see anything actionable for us here.

**Comment by ralpha** [comment]
After some testing I was able to change some of my macro's and could change the compile time from ~5m 44s to ~2m 45s.
So a reduction of 3min. This is very nice! This was just by adding:
```rust
#[cfg(feature = "postgres")]
let mut $query = $query.into_boxed::<diesel::pg::Pg>();
#[cfg(not(feature = "postgres"))]
let mut $query = $query.into_boxed::<diesel::sqlite::Sqlite>();
```
and some other minor changes that I could make because of this (mostly moving some code out of `match` blocks.)

However I noticed that there was a line in the docs ([source](https://docs.rs/diesel/1.4.5/diesel/query_dsl/trait.QueryDsl.html#method.into_boxed)):
> This is useful for cases where you want to conditionally modify a query, but need the type to remain the same. The backend must be specified as part of this. It is not possible to box a query and have it be useable on multiple backends.

But I read somewhere else ([in an other issue](https://github.com/diesel-rs/diesel/issues/882#issuecomment-305261365)) that it is not possible to have a build compiled for multiple databases?
Is this still true and if this is possible where can I find more info?

I also looked into the other improvements you suggested but do not really seem possible in my case:
* Table sizes <= 16: I already reduces everything to 32, but I used to have very big tables (100+), but splitting them up into even more tables might not be worth it as this increases the complexity of the code in other parts to much.
* Multiple subcrates: Already have 14 creates/workspaces, one of them is the for all the DB stuff. And splitting that up will not really change much as they will be somewhat interlinks and still compiled both, although it might be able to build them concurrently. But still adds some unwanted code complexity. Might look back into this if compile time is still a big issue.
* Generic functions: Not really possible I think as types differ and the current macro's are mainly focused around `match` blocks. The macro's are for user input and `order_by` and `group_by` clauses.

But with the 3min faster build I might no longer need to look into more improvements. Thanks for the info.

**Comment by weiznich** [comment]
> However I noticed that there was a line in the docs (source):
> >   This is useful for cases where you want to conditionally modify a query, but need the type to remain the same. The backend must be specified as part of this. It is not possible to box a query and have it be useable on multiple backends.
>
> But I read somewhere else (in an other issue) that it is not possible to have a build compiled for multiple databases?
Is this still true and if this is possible where can I find more info?

To clarify that a bit: It is totally possible to compile diesel itself with more than one backend enabled, it's hard to write functions accepting connections from different backends in a generic way. Diesel tries to check as much things as possible at compile time, therefore it needs to know the backend at compile time to check if the provided sql is valid for a given backend. That's done by quite a lot of trait bounds internally. If you have a function that accepts a generic type that should be a connection, you need to have as much trait bounds as required by rustc to prove that all sql inside the given function is valid for the backend of the provided connection. (That could require quite a lot of trait bounds.)

What the documentation part you've cited mean, is that it is not possible to have a boxed statement for one backend and assign the same variable a boxed statement of another backend. So explicitly this code is not possible:

```rust
let query = if backend == "postgres" {
    some::table.into_boxed::<diesel::pg::Pg>()
} else {
    some::table.into_boxed::<diesel::sqlite::Sqlite()
}
```
(Doing that at compile time via feature flags is fine)

```
