### ISSUE TITLE
Feature Request: Access to (full) Connection in Migration trait

### ISSUE THREAD

**Issue by sbrocket** [diesel-rs/diesel#2457]
The diesel::migration::Migration trait only provides access to the more limited SimpleConnection trait. This is all that's needed if you're using the CLI's migrations support and/or using diesel_migrations::embed_migrations() and defining your migrations in SQL scripts.

For a project I'm working on, I anticipate that I will want to perform migrations more complex than can be easily represented in SQL script alone. I was thinking I could still take advantage of diesel_migration's version tracking logic by defining my migrations in code, implementing the Migration trait manually for each migration, and then using diesel_migrations::run_migrations() to run then.

However, the Migration trait's run and revert methods are defined to only accept SimpleConnection, which limits me to batch_execute() rather than a fully-fledged Connection object. Can Migration be passed the full Connection instead?

**Comment by weiznich** [comment]
So the problem there is that `diesel-migration` [passes down](https://github.com/diesel-rs/diesel/blob/6242d717cdfb94ee35db50dc5abe8ec2ac238512/diesel/src/migration/mod.rs#L15) the connection used to apply the as `&dyn SimpleConnection` (as trait object). This is turn is required because `diesel_migrations` works internally with `&dyn Migration` to allow mixing different migration types. Just replacing that with `&dyn Connection` won't work as `Connection` cannot made into a trait object. Using a normal generic argument there also won't work as you then cannot continue to use `&dyn Migration` anymore.

That written I'm definitively open to someone who wants to improve that situation, but it is not something that's quite low on my personal priority list (read: That's something I can work on when I run out of other ideas, so probably not in the next few years :wink:).

**Comment by sbrocket** [comment]
Hrm, yeah, that's quite a pickle. I found a way to hack around this limitation by passing the full SqliteConnection to my Migration implementations during creation. https://github.com/sbrocket/like-scrape/commit/fed6bb404feb8d66a151cf7e66d8795cd71eaeea

My usage of Diesel is not very "serious", it's just for a personal project, so that works well enough for my purposes.
