### ISSUE TITLE
Type of query and multiple connection types

### ISSUE THREAD

**Issue by alexislozano** [diesel-rs/diesel#2476]
### Versions

- **Rust:** rustc 1.46.0-nightly (346aec9b0 2020-07-11)
- **Diesel:** 1.4.3
- **Database:** Postgres & Sqlite
- **Operating System:** Linux

### Feature Flags

- **diesel:** ["postgres", "sqlite", "chrono", "uuid"]

## Acknowledgement

First of all, thanks for Diesel, it is a really good lib !

## Problem Description

I created an enum modeling a connection to a Postgres database or a Sqlite database :
```rust
pub enum DbConn {
    PgConn(PgConn),
    SlConn(SlConn),
}

pub struct PgConn(pub r2d2::PooledConnection<ConnectionManager<PgConnection>>);
pub struct SlConn(pub r2d2::PooledConnection<ConnectionManager<SqliteConnection>>);
```
Here are two of my query structs :
```rust
pub struct ProjectQuery;

impl ProjectQuery {
    pub fn insert(
        connection: &DbConn,
        form: &CreateForm,
    ) -> QueryResult<Project> {
        let query = diesel::insert_into(projects::table).values((
            projects::user_id.eq(&form.user_id),
            projects::name.eq(&form.name),
            projects::created.eq(Utc::now().naive_utc()),
        ));
        match connection {
            DbConn::PgConn(conn) => query.get_result(&**conn),
            DbConn::SlConn(conn) => {
                query.execute(&**conn)?;
                let query = projects::table.order(projects::id.desc()).limit(1);
                query.first::<Project>(&**conn)
            }
        }
    }

    pub fn select(
        connection: &DbConn,
        id: &ProjectUuid,
    ) -> QueryResult<Project> {
        let query = projects::table.filter(projects::id.eq(id));
        match connection {
            DbConn::PgConn(conn) => query.first::<Project>(&**conn),
            DbConn::SlConn(conn) => query.first::<Project>(&**conn),
        }
    }
}

pub struct PageQuery;

impl PageQuery {
    pub fn insert(connection: &DbConn, form: &CreateForm) -> QueryResult<Page> {
        let query = diesel::insert_into(pages::table).values((
            pages::user_id.eq(&form.user_id),
            pages::project_id.eq(&form.project_id),
            pages::name.eq(&form.name),
            pages::content.eq(&form.content),
            pages::created.eq(Utc::now().naive_utc()),
        ));
        match connection {
            DbConn::PgConn(conn) => query.get_result(&**conn),
            DbConn::SlConn(conn) => {
                query.execute(&**conn)?;
                let query = pages::table.order(pages::id.desc()).limit(1);
                query.first::<Page>(&**conn)
            }
        }
    }

    pub fn select(connection: &DbConn, id: &PageUuid) -> QueryResult<Page> {
        let query = pages::table.filter(pages::id.eq(id));
        match connection {
            DbConn::PgConn(conn) => query.first::<Page>(&**conn),
            DbConn::SlConn(conn) => query.first::<Page>(&**conn),
        }
    }
}
```

As you can see, each time, I check the connection I use to execute the query, and then I use a different method of execution.

Both query structs use the same methods, I would like to make a function out of them. E.g having something like that :
```rust
fn first<U>(connection: &DbConn, query: ???) -> QueryResult<U> {
    match connection {
        DbConn::PgConn(conn) => query.first::<U>(&**conn),
        DbConn::SlConn(conn) => query.first::<U>(&**conn),
    }
}


fn insert<U>(connection: &DbConn, query: ???) -> QueryResult<U> {
    match connection {
        DbConn::PgConn(conn) => query.get_result(&**conn),
        DbConn::SlConn(conn) => {
            query.execute(&**conn)?;
            let query = projects::table.order(projects::id.desc()).limit(1); // Maybe I should also get the table from the args
            query.first::<U>(&**conn)
        }
    }
}
```

In the end I would use them on all the query structs :
```rust
pub fn select(
    connection: &DbConn,
    id: &ProjectUuid,
) -> QueryResult<Project> {
    let query = projects::table.filter(projects::id.eq(id));
    first::<Project>(connection, query);
}
```

My issue here is I cannot understand by looking at the docs what type is the query, so I'd need help writing my first and insert functions.

**Comment by weiznich** [comment]
The short answer here is: Diesel is not really designed to be used in cases where you want to change the used database backend at run time. It is explicitly not our goal to hide differences between database backend behind some sort of abstraction. You will run into issues here and as this is not a design goal non of this is documented. The probably easiest way to get something like this working is by just making the used backend a compile time option, so that you have something like `#[cfg(feature = "postgres")] type Connection = PgConnection;` somewhere.

Longer answer: Your query variable has a type that depends on which table you query, which filters you apply and so on. (You can think of query types as something like the types returned by the various iterator methods in the std-lib). So to abstract over those type you need to use generics. The generic type needs to fulfill at least all bounds listed in the type signature of the corresponding `RunQueryDsl` method, so for [`first`](http://docs.diesel.rs/1.4.x/diesel/query_dsl/trait.RunQueryDsl.html#method.first) this means `Self: LimitDsl, Limit<Self>: LoadQuery<Conn, U>, ` where `Self` is your query, `Conn` the connection type and `U` the type that implements `Queryable`. Additionally any bound that is requested by rustc needs to be added. 

Closed as I do not see anything actionable here that aligns with the project goals. Feel free to continue the discussion about this in our forum or our gitter channel.
