### ISSUE TITLE
implement FromSql and ToSql traits for url::URL

### ISSUE THREAD

**Issue by toxeus** [diesel-rs/diesel#2498]
Hi there, I'm currently migrating from `rusqlite` to `diesel`. I've noticed that there are no implementations of `FromSql` and `ToSql` for [`url::Url`](https://crates.io/crates/url). I wanted to find out if you would merge a PR implementing those traits?

**Comment by weiznich** [comment]
In general your policy for the implementation of `FromSql` / `ToSql` for certain types in diesel is something like the three following questions:

*  Is this a commonly used type. (Maybe, not sure about this one)
*  Could we provide a `FromSql` and a `ToSql` implementation for that type. (In this case Yes)
*  Could the conversion go somehow wrong because the sql type or the rust type could hold values that are not representable in the other type. (In this case the conversion from `String` to `url::Url` could go wrong, because not every arbitrary `String` is a `url`. Therefore the corresponding constructor returns a Result)

Only if we could answer those three questions with:

 *   It is a commonly used type
 *   We could provide both conversions
 *   Nothing could go wrong

we add support for those types.

As we cannot answer the third question positively I'm not in favor of having this impls. Additionally this would add yet another dependency that needs to be maintained and updated. Beside of that it is quite easy possible to provide the corresponding impls as new type wrapper in your crate.

**Comment by toxeus** [comment]
Thank you @weiznich for your precise answer :+1: I'd like to address the points you have listed.

> Is this a commonly used type.

It is a very commonly used type. The stats linked from crates.io I have provided above show that clearly. In fact, the url crate is by a factor of 18 more popular than diesel.

> Could we provide a `FromSql` and a `ToSql` implementation for that type.

Yes, these are actually quite trivial.

> Could the conversion go somehow wrong because the sql type or the rust type could hold values that are not representable in the other type. (In this case the conversion from String to url::Url could go wrong, because not every arbitrary String is a url. Therefore the corresponding constructor returns a Result)

This is a criterion that doesn't seem to apply to existing implementations, e.g. the `FromSql` implementations for `NaiveDate` and `NaiveDateTime`.

Even the `FromSql`, `ToSql` trait definitions themselves contradict that criterion because they wrap the return value in a `Result`, meaning that the conversions are expected to sometimes go wrong. Otherwise, the `Result` return type would be meaningless.

> it is quite easy possible to provide the corresponding impls as new type wrapper in your crate

That is exactly what I'm currently using. But as a good open-source citizen I have considered to contribute back to the community.

**Comment by weiznich** [comment]
>> Is this a commonly used type.
> It is a very commonly used type. The stats linked from crates.io I have provided above show that clearly. In fact, the url crate is by a factor of 18 more popular than diesel.

This question does not (only) refer to the fact how commonly used a certain type is used in the rust ecosystem but also how commonly you want to use such a type in a database. For me date/time types fullfill the definition of commonly used, while the usage `Url` types is dependent from a database point of view.

> This is a criterion that doesn't seem to apply to existing implementations, e.g. the FromSql implementations for NaiveDate and NaiveDateTime.

> Even the FromSql, ToSql trait definitions themselves contradict that criterion because they wrap the return value in a Result, meaning that the conversions are expected to sometimes go wrong. Otherwise, the Result return type would be meaningless.

`NaiveDateTime` and `NaiveDate` are supported because they are special in our opinion. A database that does not support any datetime types would be not very helpful, because datetime types are that what you would call commonly used. While Sqlite does not support a distinct type for such values on sql side, it has support for date time values. (See [here for documentation](https://sqlite.org/lang_datefunc.html)). `FromSql` and `ToSql` return a `Result` exactly for such cases where the conversion can fail, but that we are willing to implement such failing conversions in diesel itself, as we have a focus on typesafe mappings. It's more a tool for other users to implement such conversions on their own.

As another personal point against the support of `url::Url`: I've encountered a breaking change in a minor url version update in the past, therefore I'm not very keen of exposing such a dependency as part of our public API.

**Comment by toxeus** [comment]
fair enough :man_shrugging:
