### ISSUE TITLE
Cannot find macro table

### ISSUE THREAD

**Issue by Dizeeee** [diesel-rs/diesel#2537]
### Versions

- **Rust:** rustc 1.49.0-nightly
- **Diesel:** 1.4.5
- **Database:** Postgres
- **Operating System** Ubuntu 20.04

### Feature Flags

- **diesel:** postgres

## Problem Description

When I try to add a table from schema, the compiler doesn't recognize the todo! macro.

### What are you trying to accomplish?

Add a table from `schema.rs` to my project

### What is the expected output?

A successful compilation

### What is the actual output?

```
error[E0432]: unresolved import `crate::schema::employee`
 --> src/main.rs:8:5
  |
8 | use crate::schema::employee;
  |     ^^^^^^^^^^^^^^^^^^^^^^^ no `employee` in `schema`

error: cannot find macro `table` in this scope
 --> src/schema.rs:1:1
  |
1 | table! {
  | ^^^^^
```

### Are you seeing any additional errors?

No

### Steps to reproduce

My imports in `main.rs`:
```rust
#![feature(decl_macro)]

#![macro_use] extern crate diesel;
extern crate diesel_full_text_search;

mod schema;

use crate::schema::employee;

use rocket::{self, routes, get};
use diesel::{Queryable, Insertable};
use serde::{Serialize, Deserialize};
```

`schema.rs`:
```rust
table! {
    employee (id) {
        id -> Int4,
        title -> Varchar,
        checked -> Bool,
    }
}
```

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by Dizeeee** [comment]
To be clear, I have nightly for rocket dependencies, I stripped all rocket code and tested on stable before submitting.

**Comment by weiznich** [comment]
The correct syntaxt for importing the diesel macros is `#[macro_use] extern crate diesel;`. Closed as this is not an issue in diesel itself.

**Comment by DarrienG** [comment]
Just to make it clear for future searchers, as it was not obvious to me, this is required regardless of whether you are on Rust 2015, or 2018, it is required for both versions.

**Comment by jiangxiaoqiang** [comment]
I also face the same problem and my `main.rs`:

Rust: rustc 1.54.0-nightly
Diesel: 1.4.4
Database: Postgres
Operating System macOS Big Sur


```
#[macro_use] 
extern crate rocket;
extern crate diesel;
extern crate dotenv;

mod schema;
use crate::schema::*;
use diesel::{Queryable, Insertable};
use serde::{Serialize, Deserialize};
fn main(){
    //use self::schema::posts::dsl::*;
    //let connection = config::establish_connection();
}
```



and this is the `schema.rs`:


```
table! {
    posts (id) {
        id -> Int4,
        title -> Varchar,
        body -> Text,
        published -> Bool,
    }
}
```

**Comment by weiznich** [comment]
@jiangxiaoqiang Please stop adding comments to old issues, especially if your question is already answered. As written: Read the getting started guide. It has a complete example, so maybe use that as basis?

**Comment by RileySeaburg** [comment]
> @jiangxiaoqiang Please stop adding comments to old issues, especially if your question is already answered. As written: Read the getting started guide. It has a complete example, so maybe use that as basis?

Hey @weiznich your kind response is super helpful.

Please note that the getting started guide leads to the same error as stated above as of today's date. August 15, 2022.

Instead of directing your users to the documentation a more tactful approach would be to ensure that the documentation does not raise the error stated, then to reference where in the documentation the actual error is corrected or avoided and a general implementation guide on how to avoid getting that error in the future. 

It is attitudes like this that is making the Rust ecosystem not so user friendly and it goes against the core ethos of the rust language.

**Comment by weiznich** [comment]
@RileySeaburg The getting started guide is up to date as it contains the relevant `#[macro_use] extern crate diesel;` line in the literally the first line in the first rust code block. Additionally this documentation is tested in our CI + the linked examples on github also contains the relevant line. If you believe that's not true please submit a new issue. Posting on old issues like this is never a correct way to report something.

**Comment by RileySeaburg** [comment]
Welcome to who's line is it anyway, where the game is made up and the rules don't matter.

All I can say is just writing code instead of explaining the function behind it or adding descriptive comments sets people up for failure.

It's a very common practice among software developers and it really just causes the dev who manages the codebase extra time and energy explaining why they wrote it.

"If you can't explain it simply you don't understand it we'll enough."

- Albert Einstein.

P.S. We decided to switch to SQLx as it has a better community.

**Comment by weiznich** [comment]
@RileySeaburg Please stop posting such semi-aggressive comments here. They are not welcome. You are free to submit a PR improving the documentation to our webpage. It's just that different people consider different things as important part of the documentation. I personally believe that adding comments there will not help for cases where people don't even border to read the whole example. There is just no amount of documentation which could help in such cases. 

(Marking all of the last comments as off-topic as they really do not belong here at all. Feel free to continue this discussion elsewhere (for exampe in the web-sides issue tracker), but not here)
