### ISSUE TITLE
Run individual migration

### ISSUE THREAD

**Issue by himat** [diesel-rs/diesel#2577]
### Versions
- **Diesel:** 1.4.5
- **Database:** postgres

## Feature Request

Is it possible to run only `n` pending migrations instead of all of them?
Running `diesel migration run` runs all pending migrations, but I want to be able to just run one migration at a time.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Please add more information why you want to run only one migration at a time. I do not see any usecase for this. Otherwise I will close this issue as incomplete.

**Comment by weiznich** [comment]
Closed due to missing information.

**Comment by AyushSingh13** [comment]
@weiznich a request to re-open this if possible. 

I'm facing a use case where I need to add a _new_ empty table which is referenced by existing pre-populated tables.

Ideally, I'd have one migration to a) add the new table and b) `ALTER` the existing tables to add a foreign key constraint referencing the new table. However, I need to create the new table and add data to this table using an external process so that when I add the foreign key constraints to the existing tables they have data to reference.

Currently, when I try to do this, I get the following error as expected: `foreign key constraint "foreign_key_constraint_name" cannot be implemented`. Please let me know if there's already a way around this/whether I can provide any extra details about the use case!

**Comment by weiznich** [comment]
@AyushSingh13 I generally do not response (other than this) to random pings on issues that ask for updates/changes. If you want that level of support consider a support contact. Otherwise please use the official channels for such requests. In this case you would need to write a feature proposal that outlines how the suggested feature is supposed to work and at least how an implementation would look like.

**Comment by FelixSelter** [comment]
@weiznich for me the use case is automated testing. I have migrations that setup the db with its tables and migrations that insert initial prod data. I want to generate a test database with the same tables but not any of the prod data and insert test data manually

**Comment by weiznich** [comment]
@FelixSelter As written before: An old closed issue like this is the wrong place to even start discussing this, especially by cold pinging people. This is behaviour is not welcome here. If you would like to move this feature forward you are welcome to write a [feature proposal](https://github.com/diesel-rs/diesel/discussions/new?category=ideas) outlining how this feature actually is supposed to work.

**Comment by FelixSelter** [comment]
I am sorry. I did not ment this to be rude or intrusive. Thank you for clarifying the correct approach.
