### ISSUE TITLE
Document how to establish a connection

### ISSUE THREAD

**Issue by pickfire** [diesel-rs/diesel#2611]
Unless someone check the diesel website or look deep into the docs, it is hard to figure out that `Connection::establish` is used to establish a connection without looking too deep into the docs. Maybe a module level documentation (`diesel::connection` might be a good place, I find it quite empty) or crate level documentation would solve this?

My experiment source code and notes if anyone is interested. https://github.com/pickfire/diesel-multi-join-play

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
I'm not sure what you exactly expect with more in depth documentation. For us the entry point to diesel are the guides provided on our web page, where as the [Getting Started](https://diesel.rs/guides/getting-started/) guide provides a complete example how to connect to a database. 

> Maybe a module level documentation (diesel::connection might be a good place, I find it quite empty) or crate level documentation would solve this?

That's because normal users don't need to bother with this module. It's only relevant for implementing third party backends in my opinion.

Closed as I cannot see what exactly should be improved here. Feel free to submit a PR with concrete suggestions.

**Comment by pickfire** [comment]
Can you please assign this issue to me, getting started guide did provide an example but just in case a user missed that part. Some existing users may prefer going through the docs (I like it because it works offline).

What I was planning to do was to mention how to establish a connection in `diesel::connection` module (and link to getting started guide). If a user happened to browse through that module, they are able to see how to do it easily even when they are offline.
