### ISSUE TITLE
Diesel is not auto-generating a `schema.rs` file

### ISSUE THREAD

**Issue by AJTJ** [diesel-rs/diesel#2831]
### Versions

latest - **Rust:**
latest - **Diesel:**
postgresql - **Database:**
MacOS 10.15- **Operating System**

## Problem Description

Diesel is not auto-generating a `schema.rs` file.

### What are you trying to accomplish?

I'm following the "getting started" tutorial and I have connected diesel to a `postgres` db running in the official docker container. For some reason diesel is not auto-generating a `schema.rs` file.

I installed the cli with the alternative command: `cargo install diesel_cli --no-default-features --features postgres` since I ran into the `note: ld: library not found for -lmysqlclient...` error.

My DATABASE_URL looks like this: `DATABASE_URL=postgres://postgres:mysecretpassword@localhost:5432/postgres`

running the `diesel print-schema` command will show me the first table that I added to the first migration while following the tutorial:
```
table! {
    posts (id) {
        id -> Int4,
        title -> Varchar,
        body -> Text,
        published -> Bool,
    }
}
```

I'm now unable to continue with the tutorial since the `show_posts.rs` file imports the `schema.rs` file which is not being auto-generated.

Thanks

**Comment by weiznich** [comment]
This report is missing crucial information, please include them as soon as possible. Otherwise we cannot reproduce this issue.
Please include the following information:
* Exact version of rustc, diesel, diesel cli, postgresql
* The content of your `diesel.toml` file and the relative location (to the project root) of that file 

It would be useful to have additionally the following information:
* A shell script to completely reproduce this issue in a environment we have access in (for example in a docker container).

Also note that our issue tracker is not a support and help forum, so you likely wont receive any other information here than this is a bug or not. Use the forum or the gitter channel for support questions.

**Comment by AJTJ** [comment]
updating rust (to 1.53) solved this I don't think I was that far behind. Is diesel only meant to work with latest?

**Comment by mcfriend99** [comment]
```
➜  ~ cargo version
cargo 1.79.0 (ffa9cf99a 2024-06-03)
➜  ~ diesel --version
diesel 
 Version: 2.2.1
 Supported Backends: postgres mysql sqlite
```

### diesel.toml
```
# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/Users/myusername/RustroverProjects/myprojectname/migrations"
```

### Cargo.toml depencency
```
diesel = { version = "2.2.0", features = ["sqlite"] }
```

No `schema.rs` being tracked or generated. Only what I manually add to schema.rs is working.

**Comment by weiznich** [comment]
@mcfriend99 Can you please stop posting to old issues, otherwise I need to block you from the repository. Use the [discussion forum](https://github.com/diesel-rs/diesel/discussions) and provide the full context there. Consider this as your last warning, otherwise I need to block you from the organization.

**Comment by mcfriend99** [comment]
Sorry. I didn't realise commenting on an unclosed ticket with the same title as what I'm reporting will trigger you and is the criteria for getting blocked here. Close the tickets if you don't want people to comment anymore. To hell with you and your project.
