### ISSUE TITLE
Compilation error with const-generic in custom sql type 

### ISSUE THREAD

**Issue by msdrigg** [diesel-rs/diesel#2834]
### Versions

- **Rust:** 1.53.0
- **Diesel:** 1.4.7
- **Database:** Postgres
- **Operating System** Ubuntu x86_64

### Feature Flags

- **diesel:** [ "postgres" ]

## Problem Description
Compilation error occurs when trying to build custom sql type with a const-generic.

### What are you trying to accomplish?
Using diesel to derive a rust generic sized array stored in postgres backed by a postgres array.

### What is the expected output?
Compilation occurs successfully

### What is the actual output?
Compilation fails when trying to derive `AsExpression`.

### Are you seeing any additional errors?
No. I can implement `ToSql<Array<Float8>, Pg>` and `FromSql<Array<Float8>, Pg>` without errors as well.

### Steps to reproduce

Create a new project with the following files:

`**src/main.rs**`
```rust
use diesel::{
    sql_types::{Array, Float8},
    AsExpression,
};

#[derive(AsExpression)]
#[sql_type = "Array<Float8>"]
struct DoubleArray<const N: usize>([f64; N]);

fn main() {
    println!("Hello, world!");
}

```

`**Cargo.toml**`
```toml
[package]
name = "test-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
diesel = { version = "1.4" , features = ["postgres"] }
```

Execute: `cargo check` and see the following errors

> error[E0412]: cannot find type `N` in this scope

> error[E0747]: unresolved item provided when a constant was expected

I can also provide additional files like `schema.rs` if needed, but it doesn't seem necessary to produce the bug.

## Checklist

- [ x ] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [discussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
- [ x ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ x  ] This issue can be reproduced without requiring a third party crate

**Comment by msdrigg** [comment]
Followup: I may be able to take a look at this issue myself, but I don't have much experience with the diesel codebase. Where should I start?

**Comment by msdrigg** [comment]
@weiznich Is there anything blocking us from updating rust-toolchain to 1.53?

I have been working on a pr for this issue, but rust-toolchain being at 1.48 is blocking.

**Comment by msdrigg** [comment]
Well actually I don't think it's truly blocking because the const_param in the syn macro compiles fine, but it will block any testing on stable.

**Comment by weiznich** [comment]
First of all Thanks for working on this :+1:

Let me try to answer at least a few of your questions quickly:

> Is there anything blocking us from updating rust-toolchain to 1.53?

Basically the rust version set in `rust-toolchain` is the current minimal supported version. We use that to verify everything builds with that version. We normally bump this version if we need to use a new rust feature and it would otherwise be hard/impossible to implement some code. Updating to 1.53 is not required as 1.51 introduced const generic support. I wouldn't do that in a PR fixing this issue, as this would only be required for the test case then. https://github.com/diesel-rs/diesel/pull/2827 Will add support for some features based on const generics in diesel itself, so that bump will be done soon.

> Well actually I don't think it's truly blocking because the const_param in the syn macro compiles fine, but it will block any testing on stable.

I would propose the following here: Just open a per that fixes the problem + adds a test. The CI should pass independently from the minimal supported rust version update. I will hopefully be able to finish #2827 soon, so that the minimal supported version is bumped as well. After #2827 is merged it should be easy to just merge that PR then. That would save you the cost to do the compiler update (which brought up a few new warnings and lints)
