### ISSUE TITLE
Returning clause is invalid when using a custom schema

### ISSUE THREAD

**Issue by Sytten** [diesel-rs/diesel#3169]
### Versions

- **Rust: 1.60**
- **Diesel: Latest master**
- **Database: Sqlite**
- **Operating System: Linux**

### Feature Flags

- **diesel: returning_clauses_for_sqlite_3_35**

## Problem Description

Consider the schema:
```rust
    diesel::table! {
        raw.responses_raw (id) {
            id -> Integer,
            data -> Binary,
            alteration -> Text,
            source -> Text,
        }
    }
```

And the query:
```rust
let raw_id = diesel::insert_into(responses_raw::table)
                    .values(...)
                    .returning(responses_raw::id)
                    .get_result::<i32>(conn)?;
```

It will currently fail because the schema is added to the column name.

### What are you trying to accomplish?

Inserting a record and returning a column of the inserted row.

### What is the expected output?

The returning clause should be: `RETURNING id` or `RETURNING responses_raw.id`.

### What is the actual output?

It is currently: `RETURNING raw.responses_raw.id`.

### Are you seeing any additional errors?

The error returned by the database is `no such column: raw.responses_raw.id`

### Steps to reproduce

1. Open a sqlite database with path `something.db`
2. Run:
```sql
CREATE TABLE "responses_raw" (
  id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  data BLOB NOT NULL,
  alteration text NOT NULL,
  source text NOT NULL
);
```
3. Create a rust program that open a sqlite connection to another db
4. On connect it should run `ATTACH DATABASE 'something.db' AS raw;` on it
5. Add the schema provided in the problem description to your program
6. Add the query provided in the problem description to your program

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by Sytten** [comment]
I expressed some thoughts around https://gitter.im/diesel-rs/diesel?at=6273f793d4ef6e15af3062c3
But the fix really doesn't seem obvious since the schema name is really deep `StaticQueryFragmentInstance`
I feel more and more that this is a limitation of sqlite and that it should be supported since postgres does support it, so I opened https://sqlite.org/forum/forumpost/1a73dbf1a7 to discuss that.

For the meantime you can work around it by doing:
```rust
let raw_id = diesel::insert_into(responses_raw::table)
                    .values(...)
                    .returning(sql::<Integer>("id"))
                    .get_result::<i32>(conn)?;
```

I am still figuring out how to do it for all columns efficiently.

**Comment by weiznich** [comment]
Thanks for writing up this bug report. I think this might be quite easy to address as we already have some infrastructure in place to customize the SQL generation for returning clauses based on the backend. [`SqlDialect::ReturningClause`](https://docs.diesel.rs/master/diesel/backend/trait.SqlDialect.html#associatedtype.ReturningClause) let's us specify the kind of returning clause used by this database backend. Currently the `Sqlite` and the `Pg` backend share the same implementation via the [`PgLikeReturningClause`](https://docs.diesel.rs/master/diesel/backend/sql_dialect/returning_clause/struct.PgLikeReturningClause.html) marker type. This results in the following `QueryFragment` implementation then beeing used to generate the corresponding SQL fragment:
https://github.com/diesel-rs/diesel/blob/209f22ab0e519faeed174c8c384951a19497ab28/diesel/src/query_builder/returning_clause.rs#L40-L54

To address the described issue we would need to perform the following steps:
* Create a new `SqliteReturningClause` marker type in `src/sqlite/backend.rs` and set that as `SqlDialect::ReturningClause` marker type.
* Provide a bunch of `QueryFragment<Sqlite, SqliteReturningClause>` impls for `ReturningClause<Expr>` (those should be in `src/sqlite/query_builder`
* Add a test for this
* Move the now postgres specific impl to the postgres backend implementation.

The corresponding `QueryFragment` impl should look similar to that one (copied from our semi-public diesel-oci (oracle) implementation):

```rust
impl<Expr> QueryFragment<Oracle, OracleReturningClause> for ReturningClause<Expr>
where
    Expr: BindColumnList + QueryFragment<Oracle>,
{
    fn walk_ast<'b>(&'b self, mut out: diesel::query_builder::AstPass<'_, 'b, Oracle>) -> diesel::QueryResult<()> {
        out.push_sql(" RETURNING ");
        self.0.walk_ast(out.reborrow())?;
        out.push_sql(" INTO ");
        Expr::bind_column_list(out)?;
        Ok(())
    }
}

pub trait BindColumnList {
    fn bind_column_list(out: AstPass<Oracle>) -> diesel::QueryResult<()>;
}

macro_rules!  impl_bind_column_list {
    ($(
        $Tuple:tt {
            $(($idx:tt) -> $T:ident, $ST:ident, $TT:ident,)+
        }
    )+) => {
        $(
            impl<$($T: Column,)+> BindColumnList for ($($T,)+) {
                #[allow(unused_assignments)]
                fn bind_column_list(mut out: AstPass<Oracle>) -> diesel::QueryResult<()> {
                    let mut needs_comma = false;
                    $(
                        if needs_comma {
                            out.push_sql(", ");
                        }
                        let placeholder = format!(":out{}", $idx);
                        out.push_sql(&placeholder);
                        needs_comma = true;
                    )+
                    Ok(())
                }
            }
        )+
    }
}

diesel_derives::__diesel_for_each_tuple!(impl_bind_column_list);
```

Obviously that would need some adjurations to the actually generated SQL, so that just the column name is pushed as part of the helper trait + the general code is adjusted to use the `Sqlite` specific types instead of the `oracle` ones. (Just copied that code to give you an idea how that could be solved).

I would be happy to get a PR for this, especially as we now (== before the 2.0 release) can change that, but it would be really hard to go down that route afterwards (as this is a breaking change)
.

**Comment by Sytten** [comment]
I can give it a shot, though I am not sure it will cover all cases.
It would work well for the general case of using basic columns but what about a case like `RETURNING responses_raw.id, 'some_value'` or `RETURNING someFunc(responses_raw.id)`.
In rust that would look like:
```rust
sql_function!(fn transform(x: Integer) -> Text);

.returning(transform(responses_raw::id))
```

Those can't be modelled using only columns? 
We need a way to tell the inner `QueryFragment` to be aware that the column name needs to be only the name too.

**Comment by weiznich** [comment]
Yes that would only handle column names + tuples of column names for now. Anything else would be rejected at compile time. Handling the general case would be much more difficult. In fact I cannot even say if that's even possible at all.

**Comment by Sytten** [comment]
Couldn't we add metadata to the AstPass object to tell downstream objects to not print the schema name?
Only columns would react to that property, others would just pass it down.

**Comment by weiznich** [comment]
In theory that would be possible, although quite hacky. Anyway I would avoid that because that could break prepared statement cashing and compile time inlining of the query builder.

**Comment by Sytten** [comment]
Hugh annoying, I thought that would be a clever solution. I expect there are other places (Update comes to mind) could be simplified using this metadata to push down the decision to print or not the schema in the tree.

Anyway, I think giving the escape hatch of a generic `Expr` is not avoidable.
It is more common for people to not use schema and to use functions than the inverse.
So I will try to do something but I am not sure it will work, still trying to push in sqlite to support the schema name since there is no reason not to.

**Comment by weiznich** [comment]
If you are open for an experiment I might consider that option with passing down some context through the astpass to control the behavior of the `QueryFragment` impl for columns. I cannot promise that I would merge such an implementation, but I would be at least curios on the impact. My idea would be to use [`AstPass::backend`](https://docs.diesel.rs/master/diesel/query_builder/struct.AstPass.html#method.backend) for this.

For actually merging such an implementation I would require the following points:
* Does not result in a performance regression for query building of anything that does not involve a returning clause.(I would like use the trivial_query benachmark here as metric)
* The implementation is not exposed as public API via AstPass or anywhere else. Users should not be able to mess around with this.
* Maybe opt out caching prepared statements that involve such a context at all, or at least opt out using the type id as statement key in such cases.

**Comment by Sytten** [comment]
Yeah there is no rush on my end to fix this particular bug, so I will play around a bit to experiment with that idea.
The points are totally fair! I have not played with the benchmarks yet so will need to take a look.
I am also not sure about how the caching works so will need to dig into it.

**Comment by weiznich** [comment]
https://docs.diesel.rs/master/diesel/connection/statement_cache/index.html#a-primer-on-prepared-statement-caching-in-diesel has a summary on how diesel caches prepared statements. 
diesel_benches contains the benchmarks. The readme there should have some details on running them. Thats a fairly standard criterion setup. There is also a feature flag for using the instruction count instead of time as benchmark metric. They are much less noisy.
