### ISSUE TITLE
Invalid MSRV

### ISSUE THREAD

**Issue by Emm** [diesel-rs/diesel#3232]
### Versions

- **Rust:** `1.56.0` (as per `rust-toolchain`)
- **Diesel:** `5c0452eae52ebd5ec28f489ce1d395c4330936c2`
- **Database:** N/A
- **Operating System** Linux

### Feature Flags

- **diesel:** N/A

## Problem Description

Unable to cargo check the codebase:

```
info: syncing channel updates for '1.56.0-x86_64-unknown-linux-gnu'
info: latest update on 2021-10-21, rust version 1.56.0 (09c42c458 2021-10-18)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
    Updating crates.io index
  Downloaded dotenvy v0.15.1
  Downloaded clap_complete v3.2.3
  Downloaded clap v3.2.11
  Downloaded libsqlite3-sys v0.24.2
  Downloaded 4 crates (5.0 MB) in 1.12s (largest was `libsqlite3-sys` at 4.8 MB)
error: package `clap_complete v3.2.3` cannot be built because it requires rustc 1.56.1 or newer, while the currently active rustc version is 1.56.0
```

**Comment by weiznich** [comment]
Thanks for reporting this issue.

Just for the record: I do not consider this to be an issue with our MSRV, as we define MSRV as that's the rust version where diesel builds with some set of supported dependency versions. We test this by using cargos minimal-version dependency version resolution algorithm.

**Comment by Emm** [comment]
Fair enough. Should I close the PR?

**Comment by weiznich** [comment]
I think it's fine to update the rust version used in `rust-toolchain` as we have a independent check for the minimal supported rust version on the CI. I've also noted that this now needs at least 1.57 due to some other dependency + the update to the CI job might not be required anymore, as I've already done this as part of some other PR. I might be open to just switch to the latest stable release for the `rust-toolchain` version to prevent such issues from happening in the future, although that might bring other issues with breaking the clippy/rustfmt job if a new stable rust release is done.
