### ISSUE TITLE
Column type REAL for sqlite effectively broken

### ISSUE THREAD

**Issue by Randall-Coding** [diesel-rs/diesel#3645]
### Versions

- **Rust:** rustc 1.69.0-nightly (4507fdaaa 2023-02-18)
- **Diesel:** 2.0.4
- **Database:** Sqlite
- **Operating System** Ubuntu 20.04

### Feature Flags

- **diesel:** features = ["sqlite", "64-column-tables"]

## Problem Description
I created a table using REAL column types with corresponds to using an f32 in my model.  So far that's fine.  The problem arises on saving to the database where a number like 1.01 becomes 1.0900000333786.  This now makes my table unsearchable when looking for 1.01.

This seems to be a diesel problem rather than just an sqlite problem per se, since  running raw sql with rustqlite saves the value as expected, 1.01.   

### What are you trying to accomplish?
Saving a float field correctly.

### What is the expected output?
1.01

### What is the actual output?
1.0900000333786

### Are you seeing any additional errors?
No

### Steps to reproduce
1) Create a table that has a column of type REAL NOT NULL and use sqlite.
2) Create the associated model for diesel.  
3) Try to save a model with a field value of 1.01.

**Comment by Randall-Coding** [comment]
I think I've cracked the case, the information from this ticket was helpful (though not the same issue exactly) https://github.com/diesel-rs/diesel/issues/2444

It appears that diesel is converting the f32 into f64 which produces this loss of fidelity.  For now I will avoid using REAL and stick with DOUBLE which is f64 in the model and thus doesn't need to be converted into anything.

**Comment by weiznich** [comment]
Thanks for opening this issue. As your issue misses an reproducible example, I've tried to build my own:

```rust
use diesel::prelude::*;

table! {
    foo(bar) {
        bar -> Float,
    }
}

fn main() {
    let mut conn = SqliteConnection::establish("/tmp/test.db").unwrap();
    let f: f32 = 1.01;

    diesel::insert_into(foo::table)
        .values(foo::bar.eq(f))
        .execute(&mut conn)
        .unwrap();

    let mut conn = rusqlite::Connection::open("/tmp/test.db").unwrap();

    conn.execute("INSERT INTO foo(bar) VALUES (?)", [f])
        .unwrap();
}

```

This results in the following values in the `foo` table:

```
select * from foo;
1.00999999046326
1.00999999046326
```

Which means that's just the difference between inserting a `f32` and a `f64`. 

I'm closing this issue as expected behaviour + it matches that what rusqlite does for f32 values. Feel free to provide a example that demonstrates different behaviour.

**Comment by Randall-Coding** [comment]
Thanks for adding the example.  

I find it strange we'd call this expected behavior since I don't think most devs would expect their input value of 1.01 to be converted into an f64 behind the scenes and become 1.00999999046326.   

Also I think you might be mistaken regarding rusqlite, since my code was previously using rusqlite and stored that value as 1.01.

**Comment by weiznich** [comment]
> I find it strange we'd call this expected behavior since I don't think most devs would expect their input value of 1.01 to be converted into an f64 behind the scenes and become 1.00999999046326 in the db.

Well in that case please suggest what would be expected behavior given the fact that sqlite only supports 8 bit floating point values.

> Also I think you might be mistaken regarding rusqlite, since my code was previously using rusqlite and stored that value as 1.01 in the db from a model that was using f32.

I've shown my code above which produces the behavior described by me. If you believe that rusqulite behaves different: Please provide a complete example demonstrating this behavior!

**Comment by weiznich** [comment]
Thanks for providing this example. There is a fundamental difference in there: You do not store a `f32` value, but a string value. If you do the same thing in diesel you get the same result. It's not even that this behaviour is related to rusqlite, diesel or sqlite. It's just that what happens if you convert a `f32` to a `f64` as [demonstrated by this play ground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dc88fc79e9e3133f6843c437dacf7df5).

In the end it's a matter of choosing the appropriated type.
