### ISSUE TITLE
Error: r2d2 invalid URI query parameter: "pgbouncer"

### ISSUE THREAD

**Issue by palinko91** [diesel-rs/diesel#3647]
## Setup

[](https://console.neon.tech/app/projects/twilight-moon-017463/settings/databases)

### Versions

- **Rust:** 1.69
- **Diesel:** 2.1.0
- **Database:** **PostgreSQL** version: **15** (Neontech)
- **Operating System**  Windows 10 22H2

### Feature Flags

- **diesel:** ["postgres", "chrono", "serde_json", "r2d2", "uuid"]

### What are you trying to accomplish?
I want to have pooled connection to Neontech's PostgreSQL database.

### What is the expected output?
Connection. ~~But I would be satisfied also if someone would mention a free tier db hosting solution which work with Diesel's pooling cause I'm prototyping now anyway...~~

### What is the actual output?
[2023-06-01T18:30:19Z ERROR r2d2] invalid URI query parameter: "pgbouncer"

### Are you seeing any additional errors?
No

### Steps to reproduce
Okay first I've encountered the Error: prepared statement "__diesel_stmt_0" already exists" error
Then I searched and found out the PgBouncer is the error. I read the docs:
[Link to the docs](https://neon.tech/docs/connect/connection-pooling#connection-pooling-notes-and-limitations)
And found a solution. They recommending this:

 ```bash
DATABASE_URL="postgres://foo:foo@s-pooler:5432/dbname?pgbouncer=true"
```

So I guess it can set to **false** also. I did so and tried to run my program and then I've encountered this error.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Well diesel uses libpq internally an according th [their](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING) documentation `pgbouncer` is no valid uri parameter.

On a more general note: Pgbouncer is currently not supported by diesel as pgbouncer does not fully support prepared statements (as shown by the other error message). I'm open for well written proposals how to support that in diesel diesel. Otherwise you can also try to build your own connection implementation that does not assume that prepared statements work completely.

Closed as that error is expected behavior.
