### ISSUE TITLE
diesel_codegen-0.6.2 does not work with aster 0.19

### ISSUE THREAD

**Issue by flosse** [diesel-rs/diesel#368]
...beacause the function  `original_span` was removed:

https://github.com/serde-rs/syntex/commit/462e43f685db22be54c5e79b70043bb09db95d51#diff-2c9271f6ccbdf2bec8f5f03e261a0b2cL606

**update**:
It is caused by this call:
https://github.com/diesel-rs/diesel/blob/master/diesel_codegen/src/schema_inference/sqlite.rs#L48

**Comment by sgrif** [comment]
Thank you for the report. Because keeping up with nightly perpetually causes a lot of churn, our policy is currently that we will support nightlies on the dates that Rust releases. This means that the next nightly we will support will be on July 7th (because I am at a conference, it may not get updated until a few days after that date, but that will be the date we target). Thanks for your patience and understanding.
