### ISSUE TITLE
diesel_codegen doesn't compile with current nightly

### ISSUE THREAD

**Issue by aochagavia** [diesel-rs/diesel#369]
I get errors with `rustc 1.11.0-nightly (1ab87b65a 2016-07-02)`. This is probably caused by `ast::TokenTree` being moved to `tokenstream::TokenTree`.

Unfortunately, I am hitting a rustc bug and the compiler hangs indefinitely when trying to compile `diesel_codegen`, so I cannot contribute with a patch until I figure out what is going on.

**Comment by sgrif** [comment]
Thank you for the report. Because keeping up with nightly perpetually causes a lot of churn, our policy is currently that we will support nightlies on the dates that Rust releases. This means that the next nightly we will support will be on July 7th (because I am at a conference, it may not get updated until a few days after that date, but that will be the date we target). Thanks for your patience and understanding.

**Comment by aochagavia** [comment]
No problem. Thank you for the library!
