### ISSUE TITLE
diesel_codegen v0.6.2 does not build.

### ISSUE THREAD

**Issue by MrBlobbyJr** [diesel-rs/diesel#370]
`TokenTree` has been moved from `ast` to `tokenstream` in syntex_syntax recent update:
`diesel_codegen -0.6.2\src\schema_inference/mod.rs:52:12: 52:26 help: you can import it into scope: use syntax::tokenstream::TokenTree;`.

**Comment by sgrif** [comment]
Thank you for the report. Because keeping up with nightly perpetually causes a lot of churn, our policy is currently that we will support nightlies on the dates that Rust releases. This means that the next nightly we will support will be on July 7th (because I am at a conference, it may not get updated until a few days after that date, but that will be the date we target). Thanks for your patience and understanding.

**Comment by sgrif** [comment]
Ah this looks like a breaking change in a minor update actually. We may need to lock down the version further. /cc @erickt did something break in a semver incompatible way? I've gotten 3 reports about this.

**Comment by erickt** [comment]
cc @dtolnay

@sgrif: where is this crate defined? In diesel_codegen I just see 0.6.1, which is pinned to a specific syntex version, 0.31.0.

**Comment by sgrif** [comment]
Yes that's where it should be. Specifying `0.31.0` is basically `0.31.*`

**Comment by dtolnay** [comment]
@sgrif Syntex does not make breaking changes in minor updates. Cargo does not consider 0.x.0 and 0.(x+1).0 to be semver-compatible.

@MrBlobbyJr diesel_codegen builds just fine using syntex. It does not build on the latest nightly but @sgrif says that is not supported.

**Comment by sgrif** [comment]
Ok just wanted to make sure since the issue mentioned `syntex_syntax` (I'm out of the country ATM so I haven't had a ton of time). And yeah we'll update nightlies on the 7th (and likely ship 0.7.0 on that date). We'll update syntex and friends on that date as well. Thanks for looking into it @dtolnay

**Comment by porglezomp** [comment]
The policy and the date of the most recent release (perhaps with the `rustup override` invocation needed to get it) should probably be somewhere more prominent in order to prevent this confusion in the future.

**Comment by sgrif** [comment]
Yes, I will document it when I handle the next update (which will likely actually be on the 11th or 12th when I get home, but will target the nightly from the 7th assuming Rust ships today)
