### ISSUE TITLE
missing documentation through diesel macros

### ISSUE THREAD

**Issue by iamsebastian** [diesel-rs/diesel#378]
As I deny missing docs in my actual project, is it possible, to exclude this behaviour from the diesel macros?

My `schema.rs` looks like this:

``` rust
#[allow(missing_docs)]
infer_schema!(dotenv!("DATABASE_URL"));
```

... but this keeps throwing errors:

``` sh
<diesel macros>:27:33: 38:53 error: missing documentation for a module
<diesel macros>:27 ( $ ( $ column_name , ) + ) } } pub mod columns {
                                                   ^
<diesel macros>:5:1: 5:71 note: in this expansion of table_body! (defined in <diesel macros>)
src/schema.rs:2:1: 2:40 note: in this expansion of table! (defined in <diesel macros>)
src/schema.rs:2:1: 2:40 note: in this expansion of infer_schema! (defined in src/lib.rs)
src/lib.rs:1:9: 1:21 note: lint level defined here
src/lib.rs:1 #![deny(missing_docs)]
                     ^~~~~~~~~~~~
```

**Comment by sgrif** [comment]
So I can definitely add `#[allow(missing_docs)]` to the generated module (we already add `#[allow]` for anything that is a default warning), but it's worth noting that changing `#[allow(missing_docs)]` to `#![allow(missing_docs)]` would allow it for the entire `schema` module, which is probably what you want.

I'm hesitant to make this change because it can very quickly expand to pretty much any lint out there.

**Comment by killercup** [comment]
Now that we are using macros 1.1 we might be able to generate a bit of documentation for these generated modules (macro_rules macros can't do that), e.g. explaining that/when this code was generated, and add a textual description of the schema and how to use it. This might also be nice when using an IDE that can show descriptions for items.
