### ISSUE TITLE
derive(Queryable) doesn't work with a field of `Field` type

### ISSUE THREAD

**Issue by sugar700** [diesel-rs/diesel#4062]
### Versions

- **Rust:** 1.78.0
- **Diesel:** 2.2.0
- **Database:** PostgreSQL
- **Operating System** Linux

### Feature Flags

- **diesel:** none

### What are you trying to accomplish?

I'm trying use a type called `Field` in my `Queryable` data structure. In my case it has `FromSql` implementation from `Jsonb`, but in a minimal example for reproduction below I aliased `i32` to make things as simple as possible.

### What is the expected output?

It should work.

### What is the actual output?

```
error[E0106]: missing lifetime specifier
 --> src/main.rs:7:12
  |
7 |     field: Field,
  |            ^^^^^ expected named lifetime parameter
  |
  = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html

error[E0106]: missing lifetime specifier
 --> src/main.rs:7:12
  |
7 |     field: Field,
  |            ^^^^^ expected named lifetime parameter

error[E0107]: missing generics for trait `diesel::row::Field`
   --> src/main.rs:7:12
    |
7   |     field: Field,
    |            ^^^^^ expected 1 generic argument
    |
note: trait defined here, with 1 generic parameter: `DB`
   --> /home/xfix/.cargo/registry/src/index.crates.io-6f17d22bba15001f/diesel-2.2.0/src/row.rs:100:11
    |
100 | pub trait Field<'a, DB: Backend> {
    |           ^^^^^     --
help: add missing generic argument
    |
7   |     field: Field<DB>,
    |                 ++++

error[E0782]: trait objects must include the `dyn` keyword
 --> src/main.rs:7:12
  |
7 |     field: Field,
  |            ^^^^^
  |
help: add `dyn` keyword before this trait
  |
7 |     field: dyn Field,
  |            +++

Some errors have detailed explanations: E0106, E0107, E0782.
For more information about an error, try `rustc --explain E0106`.
```

### Steps to reproduce

Compile the following code.

```rust
use diesel::Queryable;

type Field = i32;

#[derive(Queryable)]
pub struct Example {
    field: Field,
}

fn main() {}
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for reporting. This is caused by a import to the `Field` trait in the relevant code generated by the `Queryable` derive here:

https://github.com/diesel-rs/diesel/blob/cc8a997ff58cd7917ba6d2c8498dcb0a7b84aec1/diesel_derives/src/queryable.rs#L49

The fix for that issue is to replace this (and all the other trait imports there) with `use diesel::row::Field as _;` to avoid the name collision. 

A fix should also add this example (maybe extended with other fields to match the other traits) as compile pass test there:

https://github.com/diesel-rs/diesel/blob/master/diesel_derives/tests/queryable.rs   

(Just having the structs + derive is sufficient for that)

It would be great to receive a PR for this.
