### ISSUE TITLE
MigrationHarness::pending_migrations() doesn't check for incompatible migrations

### ISSUE THREAD

**Issue by lxfind** [diesel-rs/diesel#4235]
https://github.com/diesel-rs/diesel/blob/master/diesel_migrations/src/migration_harness.rs#L126
When getting the list of pending migrations, it did not check that some migrations in the DB may not be part of the source migrations, i.e. incompatible. We should error out there if the remove failed.

**Comment by weiznich** [comment]
Please use the provided bug template if you want to fill an issue, otherwise this will be closed as invalid.

Otherwise you really need to explain why we should change the existing behavior there, as this function exactly behaves as described: It returns a list of migrations that are not applied to the database yet, which is still true if the source doesn't contain all migrations that are applied to the database.

**Comment by weiznich** [comment]
Closed due to no response from @lxfind. Feel free to edit the issue later to add the requested details, otherwise this is just not an issue.
