### ISSUE TITLE
`diesel` with `64-column-tables` can not be built on `nightly-2024-10-20`

### ISSUE THREAD

**Issue by vnghia** [diesel-rs/diesel#4315]
### Versions

- **Rust:** `nightly-2024-10-20`
- **Diesel:** `2.2.4`
- **Database:** `Postgresql`
- **Operating System** `Debian`

### Feature Flags

- **diesel:** `64-column-tables`
- **diesel-async:** `postgres`

## Problem Description
Can not be built if both `64-column-tables` and `postgres` are enabled. If `64-column-tables` it will compile fine.

### What are you trying to accomplish?
Build `diesel`

### What is the expected output?
Build successfully

### What is the actual output?
You can read the log [here](https://github.com/vnghia/diesel-nightly-2024-20-10/actions/runs/11426473113/job/31789431846)

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate

## Additional information
I could send a fix if you can point me to somewhere. If this issue is invalid because of nightly channel, could you convert it to a discussion and point me somewhere to fix this ? Thank you very much!

**Comment by weiznich** [comment]
>  If this issue is invalid because of nightly channel, could you convert it to a discussion and point me somewhere to fix this 

The check list literally says: 

>  This issue can be reproduced on Rust's stable channel. (Your issue will be
closed if this is not the case)

So yes, this issue is invalid and will be closed.

> point me somewhere to fix this

Given that it works on stable rust and it does not work on nightly rust the correct place to fix that is https://github.com/rust-lang/rust/
Given that I do not really see any reason to keep this as discussion.

I've filled https://github.com/rust-lang/rust/issues/131969 for that, so please follow that other issue. In the future: If you ever hit such a regression again fill the bug report directly in the rustc repo.
