### ISSUE TITLE
Rename `options` decorator

### ISSUE THREAD

**Issue by SergioBenitez** [diesel-rs/diesel#558]
Rocket uses `options` as a decorator to declare an HTTP `options` route. Diesel uses it to declare options on schemas. This causes a collision when the two libraries are used together, resulting in a compilation error.

It seems that the `options` decorator isn't used frequently by end-users in Diesel, while `options` in Rocket is one of the core decorators. Would you consider renaming `options` to `schema_options` or `table_options`, or something else, so that the two can coexist before macro renaming is allowed?

**Comment by killercup** [comment]
FTR: Since macros 1.1 does not allow supplying parameters to the derive calls itself, we unfortunately need to deal with attribute namespacing. Diesel already does a bit of that with attributes like `changset_options` and less generic names like `table_name`, or `primary_key`, but I can see that `options` is a problem.

Luckily, as you note, this should not be a user-facing breaking change. The options attribute is only used in the macros `infer_schema!`, `infer_schema_from_table!`, and `embed_migrations!`. I would accept a PR to change these attribute names to something more specific, like `infer_schema_options`, `infer_table_from_schema_options`, and `embed_migrations _options`.

It should suffice to change the names [here](https://github.com/diesel-rs/diesel/blob/47d1196c4416023e47cabaeba903d5b50bfd3dcc/diesel_codegen/src/lib.rs#L61), [here](https://github.com/diesel-rs/diesel/blob/8ec06aa37c09d77c238dd96a43ee3aea6deefb0f/diesel/src/macros/macros_from_codegen.rs), and [here](https://github.com/diesel-rs/diesel/blob/0ce23eb8e6c36371308342fb8407d99b553b5556/diesel_codegen/src/util.rs#L104).

**Comment by sgrif** [comment]
BTW https://github.com/SergioBenitez/Rocket/blob/24805bbf16d25a21d6a926c86035ac905524c71c/scripts/test.sh#L80-L84 I super promise everything is fine now. Macros 1.1 fixed everything.
