### ISSUE TITLE
Add instructions for building diesel_cli

### ISSUE THREAD

**Issue by Timmmm** [diesel-rs/diesel#588]
It seems like the default build of diesel_cli tries to link with postgres *and* sqlite. I'd guess a lot of people only have one and I had to guess how to build it without sqlite support.

Maybe add something like this:

> Instead, we just install it on our system.
>
>     cargo install diesel_cli
>
> By default this will build support for PostgreSQL and SQLite. If you only have one installed you can avoid compilation errors by building `diesel_cli` like this.
>
>     cargo install diesel_cli --features "postgres" --no-default-features
>
> Or
>
>     cargo install diesel_cli --features "sqlite" --no-default-features

I was going to do a pull request but can't find the github repo for the website.

**Comment by killercup** [comment]
First off, it shouldn't hurt to have both: Most people will use postgres in production, and enabling support for sqlite should not be a problem.

I saw you had problems (#587) getting postgres (or, more specifically pg-sys) to work on Windows, so maybe we should also link to this. (We are planning on using our own postgres driver in the future, by the way, which will not need linking to libpg.)

The sources of diesel.rs are here: https://github.com/sgrif/diesel.rs-website (it's not in this orga because of something about github pages and DNS setup IIRC). It might make more sense to explain the available features in diesel_cli's Readme ([here](https://github.com/diesel-rs/diesel/blob/master/diesel_cli/README.md)), though, and only link to that on the website.

**Comment by killercup** [comment]
Seems to be resolved by sgrif/diesel.rs-website#29.
