### ISSUE TITLE
Empty changeset is still executed, fails.

### ISSUE THREAD

**Issue by Boscop** [diesel-rs/diesel#598]
When an update is done with an empty changeset (all options None), it still tries to execute the query (which fails, at least with postgres), maybe that should be prevented earlier?

**Comment by sgrif** [comment]
This should have been fixed in 0.9. Can you provide a script to reproduce?

**Comment by Eijebong** [comment]
I just tried it and got
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QueryBuilderError(StringError("There are no changes to save. This query cannot be built"))', /checkout/src/libcore/result.rs:860:4
```
I think this can be closed as we can't detect that there are no changes earlier than that.

@Boscop Feel free to reopen if you think I'm wrong

**Comment by sgrif** [comment]
Just to clarify on why it is important that this is an error case, while inserting an empty vector is not:

When you insert 0 rows, we always know exactly how to replicate the behavior that would have otherwise occurred (`execute` returns `Ok(0)`, `get_results` returns `Ok(Vec::new())`, and `get_result` returns `Err(NotFound)`). That is not the case with a changeset with no changes.

In the absolute simplest case we'd need to do the equivalent `SELECT` statement to figure out what to return, but even that is insufficient. We'd also need to vary our behavior based on whether the changeset given was attempting to use upsert. Even with all of that, the triggers executed could potentially change the outcome as well.

**Comment by csharad** [comment]
#[macro_use] extern crate diesel;
    #[macro_use] extern crate diesel_codegen;
    extern crate dotenv;

    use diesel::prelude::*;
    use diesel::mysql::MysqlConnection;
    use dotenv::dotenv;
    use std::env;
    use schema::numbers;
    pub fn establish_connection() -> MysqlConnection {
        dotenv().ok();

        let database_url = env::var("DATABASE_URL")
            .expect("DATABASE_URL must be set");
        MysqlConnection::establish(&database_url)
            .expect(&format!("Error connecting to {}", database_url))
    }

    mod schema {
        infer_schema!("dotenv:DATABASE_URL");
    }

    #[derive(Debug, Queryable)]
    struct Number {
        id: i32,
        number: i32
    }

    #[derive(Insertable)]
    #[table_name="numbers"]
    pub struct NewNumber {
        number: i32
    }

    #[derive(AsChangeset)]
    #[table_name="numbers"]
    pub struct ChangeNumber {
        number: Option<i32>
    }

    fn main() {
        let connection = establish_connection();
        let results = numbers::table.limit(5).load::<Number>(&connection).expect("error");
        println!("{:?}", results);
    
        let n = NewNumber { number: 1 };
        diesel::insert(&n).into(numbers::table).execute(&connection).expect("errr");
    
        let change = ChangeNumber { number: None };
        diesel::update(numbers::table.find(1)).set(&change).execute(&connection).unwrap(); 
    }

This code ends up with the same error but for `mysql`.
