### ISSUE TITLE
Macros need more documentation.

### ISSUE THREAD

**Issue by quadrupleslap** [diesel-rs/diesel#730]
Why are they all `#[doc(hidden)]`? Are we not supposed to use them?

**Comment by killercup** [comment]
What macros are you specifically talking about?

Some of them are explicitly not public API (so we can have breaking
changes) and are only used by the code gen crate, or internally.

Ram Kaniyur <notifications@github.com> schrieb am Sa. 18. Feb. 2017 um
11:32:

**Comment by sgrif** [comment]
Yes, if something is `#[doc(hidden)]`, you aren't supposed to use them, and they're not meant to be public API. Often times we have to make things public from the Rust point of view (either marked as `pub` or `#[macro_export]`) because we are using that type/macro inside of a macro which *is* public API. If something is marked as `#[doc(hidden)]`, that is our way of indicating that you aren't meant to use it. If there's a specific macro that you think should be public API, please let me know.
