### ISSUE TITLE
Trait error when running MySQL example

### ISSUE THREAD

**Issue by HarmonEpsilon** [diesel-rs/diesel#826]
Every time I try building the provided MySQL example, I encounter the following error:

```
error[E0277]: the trait bound `i32: diesel::types::FromSqlRow<diesel::types::BigInt, di
esel::mysql::Mysql>` is not satisfied
  --> src\lib.rs:38:28
   |
38 |     posts.order(id.desc()).first(conn).unwrap()
   |                            ^^^^^ the trait `diesel::types::FromSqlRow<diesel::type
s::BigInt, diesel::mysql::Mysql>` is not implemented for `i32`
```

I initially thought it was a bug with the nightly build from 2017-03-16, but when running on stable, I encounter the same error. 
Info:
rustc 1.17.0-nightly
cargo 0.18.0-nightly
Diesel version 0.12.0

**Comment by ggrochow** [comment]
It looks like your database table wasn't created with the correct id Integer type. Could you post your up.sql file from the migration that created the table?

The issue here appears to be your `id` field is a (BigInt)[http://docs.diesel.rs/diesel/types/struct.BigInt.html] which converts into a rust `i64` not `i32`

I was able to pass all the tests for this example locally (by cloning the repo, and running the [test_all script](https://github.com/diesel-rs/diesel/tree/master/examples/mysql))

**Comment by HarmonEpsilon** [comment]
Sure thing.

```
CREATE TABLE posts (
  id INTEGER PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  body TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT FALSE
);
```

I also cloned the repo and tried compiling Part 3 of the MySQL example and ran into the same problem.

**Comment by ggrochow** [comment]
Could you try to [`diesel database reset`](https://github.com/diesel-rs/diesel/tree/master/diesel_cli#database-reset) that example database, and give it a shot.

If that doesn't solve the issue, could you let us know the mysql version + OS you are using? 
and if any of the other db-backends examples dont work?

**Comment by HarmonEpsilon** [comment]
There it goes. It's working now. Thanks.
