### ISSUE TITLE
Request: macros for making `NewPost` and `Post` structs less redundant

### ISSUE THREAD

**Issue by rbalicki2** [diesel-rs/diesel#919]
Would it be possible for diesel to provide macros so that if I have two models, say `Post` and `NewPost`, which differ only in that `Post` also has an `id` field, I could define them using only a single struct?

e.g.

```
#[alsoDefineNew]
pub struct Post {
  #[excludeInNew] id: i32,
  title: String,
}
```

And now, there is a `NewPost` struct as well.

I've thought about doing this with traits, but it ends up being very redundant and OOP in a java-like way. Macros could probably help, though.

This is far above my pay grade right now, but I wanted to make this request - perhaps it already exists or is in the pipeline :)

**Comment by rbalicki2** [comment]
Come to think of it, this is not really core to diesel's mission. It's probably better as an external library. It might need to know about diesel's Insertable, etc. derivations, but otherwise would probably be best as a separate library.

**Comment by Eijebong** [comment]
Have a look at #860 too ^^

**Comment by behos** [comment]
I've created something along these lines for the new structure here

https://github.com/behos/models-derive

Used like https://github.com/behos/models-derive/blob/master/tests/default_insertable.rs#L20

but i haven't published this as a crate since I'm not 100% sure it's complete. I'd be happy to get some feedback and ideas/contributions around that
