### ISSUE TITLE
`get_result`  return err `NotFound`  when upsert on_conflict do_nothing

### ISSUE THREAD

**Issue by zhangsoledad** [diesel-rs/diesel#952]
- diesel 0.13.0  

- rust 1.18 stable

```rust
User<'a> {
   name: &'a str
}

fn save(user: User) -> Result {
    match diesel::insert(&user.on_conflict(users::name, do_nothing()))
                .into(users::table)
                .get_result::<User>(conn) {
        Ok(_) => Ok(()),
        Err(e) => {
            debug!("save user {:?}", e);
            Err(e)
        }
    }
}

save(User{name: "123"}).unwrap(); //ok
save(User{name: "123"}).unwrap(); //wrong get NotFound
```

is this by design?

**Comment by sgrif** [comment]
It's a bit of a quirky interaction between those two features, but yeah it's by design. I don't think that specifically passing an upsert with `do_nothing` to `insert` should change the return type of `get_result`, as that's a really non-local change. You should call `.optional` here if you want a `QueryResult<Option<User>>` [as per the docs](http://docs.diesel.rs/diesel/prelude/trait.LoadDsl.html#tymethod.get_result)

**Comment by tbarusseau** [comment]
Hello! I'm glad to see that this has been addressed, because I had the same question.

Using `.optional`, however, returns `Ok(None)`, which is truthy... But it feels like it shouldn't be, why isn't it `Err(Some(Conflict))` (even though `Conflict` doesn't exist)? Am I missing something?

For reference, this is the code that returns `Ok(None)` when there is a conflict on `nickname` (which is a unique key):

```rust
    diesel::insert_into(users::table)
        .values(InsertableUser {
            password: &encode(&hashed_password),
            ..user
        })
        .on_conflict(users::columns::nickname)
        .do_nothing()
        .get_result(connection)
        .optional()
```

**Comment by weiznich** [comment]
@tbarusseau That just mirrors the behavior of the underlying database. We return `Error::NotFound` (which is converted to `Ok(None)` by `.optional()`) only for cases where we get back no error and empty result set from the database. So there is really no way for us detecting that to happen here.

**Comment by tbarusseau** [comment]
What I don't get specifically is why `Error::NotFound` is returned on conflict, is it because the database actually responds an empty result set (because of the conflict)?

**Comment by weiznich** [comment]
@tbarusseau Yes, exactly that happens. The database returns an empty result set (likely because of the conflict), diesel turns that as part of the `get_result` implementation into `Err(Error::NotFound)` and `.optional()` then turns this into `Ok(None)`.

**Comment by tbarusseau** [comment]
I see :) Thanks for the explanation
